#! /usr/bin/env python
'''=Swept Shapes (lathe, spiral, screw, tubes)=

[extrusions_shapes.py-screen-0001.png Screenshot]

Every swept geometry node in one scene, so the difference between them can
be read off against what each one looks like. All of it is generated by
`opengl_extrusions` as plain vertex arrays, which is why these render in
**either profile** -- a shader pass draws them as an indexed mesh, a
compatibility pass draws the same arrays through the fixed-function
pipeline.

Left to right:

 * *Lathe* -- a square section carried around the z axis with its plane
   staying radial, climbing as it goes. The section stays upright however
   steep the climb, which is what makes this the shape of a screw thread.
 * *Spiral* -- the same parameters, but the section's plane stays square
   to the path and tilts with the climb. This is what a coiled length of
   wire does, and beside the lathe the difference is plain.
 * *Screw* -- a square extruded along z while turning: a drill bit.
 * *Toroid* -- a circle swept a full turn, which is a torus.
 * *PolyCylinder* -- a round tube of constant radius following a bent
   path, mitred at the corner so the surface stays continuous.
 * *PolyCone* -- the same path with a radius given at every point, so the
   tube tapers from one end to the other.

Use the arrow keys and the mouse to walk around them.
'''
from math import pi

from OpenGLContext import testingcontext
BaseContext = testingcontext.getInteractive()

from OpenGLContext.scenegraph.basenodes import (
    Appearance, DirectionalLight, Material, PointLight, PolyCone, PolyCylinder,
    Shape, Transform, Viewpoint, sceneGraph,
)
from OpenGLContext.scenegraph.extrusions import Lathe, Screw, Spiral

#: A square section for the rotational sweeps, read as (out from the axis, up).
SECTION = [(0.0, -0.12), (0.24, -0.12), (0.24, 0.12), (0.0, 0.12)]

#: A circle for the toroid, in the same r-z plane.
def circle_section(radius=0.18, sides=16):
    from opengl_extrusions import circle
    return circle(radius, sides)

#: The bent path the two tubes follow.
TUBE_PATH = [(0.0, -1.2, 0.0), (0.0, 0.2, 0.0), (1.0, 1.2, 0.0)]

COLOURS = {
    'brass': (0.78, 0.60, 0.22),
    'steel': (0.62, 0.66, 0.70),
    'copper': (0.72, 0.42, 0.28),
    'green': (0.35, 0.62, 0.38),
}


def look(colour):
    return Appearance(material=Material(diffuseColor=COLOURS[colour],
                                        shininess=0.6))


class TestContext(BaseContext):
    """Every swept node, three across and two down."""

    def OnInit(self):
        shapes = [
            ('brass', Lathe(contour=SECTION, startRadius=0.9, deltaZ=0.9,
                            totalAngle=4 * pi, sides=48)),
            ('copper', Spiral(contour=SECTION, startRadius=0.9, deltaZ=0.9,
                              totalAngle=4 * pi, sides=48)),
            ('steel', Screw(contour=[(-0.3, -0.3), (0.3, -0.3), (0.3, 0.3),
                                     (-0.3, 0.3)],
                            startZ=-1.4, endZ=1.4, totalAngle=6 * pi)),
            ('green', Lathe(contour=circle_section(), startRadius=1.0,
                            totalAngle=2 * pi, sides=48)),
            ('steel', PolyCylinder(path=TUBE_PATH, radius=0.28, sides=24,
                                   join='angle')),
            ('copper', PolyCone(path=TUBE_PATH, radii=[0.42, 0.26, 0.10],
                                sides=24, join='angle')),
        ]
        children = []
        across, spacing = 3, 3.4
        for index, (colour, geometry) in enumerate(shapes):
            column, row = index % across, index // across
            children.append(Transform(
                translation=((column - 1) * spacing, (0.5 - row) * spacing, 0),
                # The rotational sweeps are built in the plane about z; tip them
                # toward the camera so the climb reads as a climb.
                rotation=(1, 0, 0, -1.15) if index < 4 else (0, 1, 0, 0.4),
                children=[Shape(geometry=geometry, appearance=look(colour))],
            ))
        children.append(Viewpoint(position=(0, 0.4, 11.5)))
        children.append(PointLight(location=(6, 9, 12)))
        children.append(DirectionalLight(direction=(-0.4, -0.8, -0.5),
                                         color=(0.45, 0.45, 0.5)))
        self.sg = sceneGraph(children=children)


if __name__ == '__main__':
    TestContext.ContextMainLoop()
