# Terrain asset formats & heightmap provenance

How the `SplatTerrain` / `HeightField` engine consumes its inputs, and exactly how
the forest demo's heightmap and splat control map were produced from real DEM data.

The demo's heightmap and control map were generated by **ad-hoc scripts** during
development, not a committed tool. This document is the record of that process and
the format contract, so the assets are reproducible. The snippets below are complete
and runnable.

---

## 1. Heightmap (`forest_height.png`)

### Source

Public **AWS Terrain Tiles** (Mapzen/Terrarium encoding), an open aggregate of SRTM,
USGS 3DEP and other sources, served as slippy-map PNG tiles:

```
https://s3.amazonaws.com/elevation-tiles-prod/terrarium/{z}/{x}/{y}.png
```

Each tile is an 8-bit RGB PNG that encodes elevation in metres:

```
elevation_m = R * 256 + G + B / 256 - 32768
```

### The demo's heightmap

Region: **Great Smoky Mountains** (heavily forested, rolling ridges, moderate relief
— walkable), centred at **lat 35.60, lon −83.50**, zoom **z = 12**, a **4×4** tile
mosaic → **1024×1024** px. Fetch → stitch → Terrarium-decode → normalise the
elevation span to the full 16-bit range → save as a 16-bit grayscale PNG:

```python
import urllib.request, math, io
import numpy as np
from PIL import Image

lat, lon, z = 35.60, -83.50, 12          # Great Smoky Mountains
G = 4                                     # 4x4 tiles -> 1024x1024

def deg2tile(lat, lon, z):                # slippy-map / Web-Mercator
    n = 2 ** z
    x = (lon + 180) / 360 * n
    y = (1 - math.log(math.tan(math.radians(lat)) + 1 / math.cos(math.radians(lat))) / math.pi) / 2 * n
    return x, y

xf, yf = deg2tile(lat, lon, z); xc, yc = int(xf), int(yf)
base = "https://s3.amazonaws.com/elevation-tiles-prod/terrarium/%d/%d/%d.png"
tiles = {}
for dy in range(-G // 2, G // 2):
    for dx in range(-G // 2, G // 2):
        req = urllib.request.Request(base % (z, xc + dx, yc + dy), headers={"User-Agent": "oglc"})
        with urllib.request.urlopen(req) as r:
            tiles[(dx, dy)] = np.asarray(Image.open(io.BytesIO(r.read())).convert("RGB")).astype(np.float64)
img = np.concatenate([np.concatenate([tiles[(dx, dy)] for dx in range(-G // 2, G // 2)], 1)
                      for dy in range(-G // 2, G // 2)], 0)

elev = img[..., 0] * 256 + img[..., 1] + img[..., 2] / 256 - 32768     # metres
h = (elev - elev.min()) / (elev.max() - elev.min())                     # -> 0..1
Image.fromarray((h * 65535).astype(np.uint16)).save("forest_height.png") # 16-bit grayscale
np.save("forest_elev.npy", elev)                                        # keep metres for the control map
```

Note the heightmap is **normalised** (min→0, max→65535): it stores *shape*, not
absolute metres. The world vertical scale is set separately by `relief` at load
time (see below), so `relief` is an authoring choice (a compressed/exaggerated
relief), not the DEM's true metre span.

### Format & how the engine consumes it

- **File:** 16-bit grayscale PNG (`mode I;16`), here 1024×1024. Any square size works.
- **Loader:** `HeightField.from_image(path, res, extent, relief)`
  (`OpenGLContext/scenegraph/terrain/heightfield.py`):
  - resamples the image to `res × res` (the demo uses `RES = 513`, the mesh grid);
  - `grid = pixel_value / 65535.0` → normalised `0..1`;
  - `extent` = world side length in metres (demo `EXTENT = 4096`), centred on the
    origin, so world XZ spans `[-extent/2, extent/2]`;
  - `relief` = world height of a full `0→1` change (demo `RELIEF = 450`).
- **Sampling:** `HeightField.sample(x, z)` is bilinear and maps world→texel as
  `u = (x + extent/2)/extent · (res−1)`, `v = (z + extent/2)/extent · (res−1)`,
  indexing `grid[v, u]`. So **image column = +X, image row = +Z**; row 0 (top of the
  image) is the `z = −extent/2` edge. World height = `bilerp(grid) · relief`.

The camera clamp, tree/grass placement, slope and shadow bake all sample through
this one `HeightField`, so they sit on exactly the surface the mesh renders.

---

## 2. Splat control map (`forest_control.png`)

### Format & how the engine consumes it

- **File:** 8-bit **RGBA** PNG (demo 1024×1024). One channel per splat layer, in the
  order the terrain node is given its `layers`.
- **Channel → layer:** the demo's `LAYERS = ["forest_floor", "grass", "rock", "moss"]`
  map to **R = forest_floor, G = grass, B = rock, A = moss**.
- **Meaning:** each channel is that layer's blend **weight** at that point. The
  fragment shader (`shaders/terrain_splat.frag`) samples the control map by the same
  world→texel mapping as the heightmap
  (`uv = (worldXZ − worldMin)/worldSize`, `worldMin = −extent/2`, `worldSize = extent`),
  then **normalises** `w /= (w.r+w.g+w.b+w.a)` and blends the layers' detail
  textures by those weights. Weights need not pre-sum to 1 (the shader normalises),
  but the demo's do.
- Up to 4 layers (RGBA). `numLayers` tells the shader how many are live.

### How the demo's control map was generated

Derived from the **same DEM** — slope + normalised elevation + a low-frequency
break-up noise decide the biome weights, then normalised to sum to 1 per texel:

```python
import numpy as np
from PIL import Image

elev = np.load("forest_elev.npy"); N = elev.shape[0]
h = (elev - elev.min()) / (elev.max() - elev.min())               # 0..1 elevation
gy, gx = np.gradient(elev); slope = np.hypot(gx, gy)
s01 = np.clip(slope / np.percentile(slope, 97), 0, 1)             # normalised slope
rng = np.random.default_rng(4)                                    # low-freq break-up
brk = np.asarray(Image.fromarray((rng.random((150, 150)) * 255).astype(np.uint8))
                 .resize((N, N), Image.BILINEAR)).astype(float) / 255

rock  = np.clip((s01 - 0.62) / 0.25, 0, 1)                        # steep ground
grass = np.clip((1 - s01 * 1.5) * (0.55 + 0.5 * brk), 0, 1)       # gentle slopes
wet   = np.clip((0.10 - h) / 0.10, 0, 1) * np.clip(1 - s01 * 2.5, 0, 1)  # low + flat -> moss
floor = np.clip(1 - (rock + grass * 0.75 + wet), 0, 1) * np.clip(0.35 + brk * 0.6, 0, 1) + 0.02

ctrl = np.stack([floor, grass, rock, wet], -1)                    # R,G,B,A = layer order
ctrl = ctrl / np.clip(ctrl.sum(-1, keepdims=True), 1e-4, None)    # normalise to 1
Image.fromarray((ctrl * 255).astype(np.uint8), "RGBA").save("forest_control.png")
```

The control map is a **generated** asset (CC0). Hand-painting one in an image editor
(one layer per channel) works equally well — the engine only cares about the RGBA
weight contract above.

---

## 3. Detail layer materials

The layers themselves are not bundled: `SplatTerrain(height_field, layers, control)`
resolves each layer name through `material_fn` (default the cc0/ambientCG fetcher) to
**color / normal / roughness** maps, uploaded as three `GL_TEXTURE_2D_ARRAY`s (one
slice per layer). The shader tiles them at two frequencies (`detailScale` +
`macroScale`) and blends by the control weights, so the control map is low-resolution
(per-region biome) while the ground stays crisp up close. These are CC0 (no
attribution required); see the demo's `ASSET-LICENSES.md`.

---

## 4. Making a new terrain (recipe summary)

1. Pick a lat/lon/zoom, fetch the Terrarium mosaic, decode + normalise → 16-bit
   grayscale PNG (§1). Keep the metres array for step 2.
2. Build an RGBA control map — from slope/elevation rules (§2) or by hand — one
   channel per detail layer, in your `LAYERS` order.
3. `hf = HeightField.from_image(height_png, res, extent, relief)`;
   `SplatTerrain(hf, LAYERS, control_png)`. Tune `extent` (footprint) and `relief`
   (vertical scale) to taste.

**Possible follow-up:** fold §1–§2 into a committed `forest-demo/tools/make_terrain.py`
(mirroring `tools/bake_assets.py`) so the terrain assets are regenerable by command,
not just by this recipe.
