#!/bin/bash
# Deprecated. Tutorials are generated by docs/build.sh (which runs the directdocs
# extractor) into docs/tutorials/, committed, and published with the rest of the
# site by GitHub Pages. There is no separate upload step any more.
echo "docs/uploadtutorials.sh is deprecated; run 'bash docs/build.sh' instead."
