"""What a registry of content packs will and will not accept.

Validation is strict because the failure it guards against is silent: an entry
with a mistyped key that is accepted, ignored, and never noticed is a pack
nobody can download and nobody can see the absence of. Every case here is a
refusal with a reason, or an entry that survives with the values it declared.
"""

import json

import pytest

from OpenGLContext.contentpacks import catalog
from OpenGLContext.contentpacks.pack import ContentPack


ENTRY = {
    'key': 'glisteel/ashdown',
    'title': 'Ashdown',
    'url': 'https://example.invalid/ashdown.tar.gz',
    'directory': 'ashdown',
    'archive': 'tar',
    'approximate_bytes': 32 * 1024 * 1024,
    'copyright': 'Generated by OpenGLContext (BSD-3-Clause)',
    'marker': 'tileset.json',
}


def registry(tmp_path, *entries, namespace='glisteel', name='packs.json'):
    """A registry file holding ``entries``, with anything missing filled in."""
    packs = [dict(ENTRY, **entry) for entry in (entries or [{}])]
    path = tmp_path / name
    path.write_text(json.dumps({'namespace': namespace, 'packs': packs}),
                    encoding='utf-8')
    return str(path)


class TestAnEntryThatIsAccepted:
    def test_it_arrives_with_what_it_declared(self, tmp_path) -> None:
        pack, = catalog.load(registry(tmp_path))
        assert isinstance(pack, ContentPack)
        assert pack.key == 'glisteel/ashdown'
        assert pack.approximate_bytes == 32 * 1024 * 1024
        assert pack.marker == 'tileset.json'

    def test_what_it_leaves_out_takes_a_default(self, tmp_path) -> None:
        pack, = catalog.load(registry(tmp_path))
        assert pack.sha256 == ''
        assert pack.base is False
        assert pack.needs == ()
        assert pack.family is None

    def test_needs_is_a_tuple_whatever_json_gave(self, tmp_path) -> None:
        """A list from JSON, a tuple on the value: packs are hashable."""
        pack, = catalog.load(registry(
            tmp_path, {'needs': ['glisteel/forest-art']}))
        assert pack.needs == ('glisteel/forest-art',)
        hash(pack)

    def test_the_order_of_the_file_is_kept(self, tmp_path) -> None:
        """A chooser shows them in the order somebody wrote them."""
        path = registry(tmp_path,
                        {'key': 'glisteel/one'}, {'key': 'glisteel/two'},
                        {'key': 'glisteel/three'})
        assert [pack.key for pack in catalog.load(path)] == [
            'glisteel/one', 'glisteel/two', 'glisteel/three']


class TestAnEntryThatIsRefused:
    def test_a_field_no_field_is_called(self, tmp_path) -> None:
        """The case strictness exists for: a typo that would be ignored."""
        path = registry(tmp_path, {'aproximate_bytes': 5})
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(path)
        assert 'aproximate_bytes' in str(raised.value)

    @pytest.mark.parametrize('field', sorted(catalog.REQUIRED))
    def test_a_required_field_left_out(self, tmp_path, field) -> None:
        entry = {name: value for name, value in ENTRY.items() if name != field}
        path = tmp_path / 'packs.json'
        path.write_text(json.dumps({'namespace': 'glisteel',
                                    'packs': [entry]}), encoding='utf-8')
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(str(path))
        assert field in str(raised.value)

    def test_a_pack_that_states_no_terms(self, tmp_path) -> None:
        """The notices screen is generated from `copyright`."""
        path = registry(tmp_path, {'copyright': '   '})
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(path)
        assert 'copyright' in str(raised.value)

    @pytest.mark.parametrize('size', [0, -1])
    def test_a_pack_that_states_no_size(self, tmp_path, size) -> None:
        """The size is what the user consents to and what caps the fetch."""
        with pytest.raises(catalog.BadCatalog):
            catalog.load(registry(tmp_path, {'approximate_bytes': size}))

    def test_an_archive_kind_nothing_reads(self, tmp_path) -> None:
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(registry(tmp_path, {'archive': 'rar'}))
        assert 'rar' in str(raised.value)

    def test_a_url_that_is_not_http(self, tmp_path) -> None:
        """A registry names what to fetch, not what to open on this machine."""
        with pytest.raises(catalog.BadCatalog):
            catalog.load(registry(tmp_path, {'url': 'file:///etc/shadow'}))

    def test_a_directory_that_climbs_out_of_the_store(self, tmp_path) -> None:
        """`directory` is joined against the store, so it is one segment."""
        for bad in ('../elsewhere', '/absolute', 'nested/path'):
            with pytest.raises(catalog.BadCatalog):
                catalog.load(registry(tmp_path, {'directory': bad}))

    def test_a_file_that_is_not_a_registry(self, tmp_path) -> None:
        path = tmp_path / 'packs.json'
        path.write_text('this is not json', encoding='utf-8')
        with pytest.raises(catalog.BadCatalog):
            catalog.load(str(path))

    def test_a_file_that_is_not_there(self, tmp_path) -> None:
        with pytest.raises(catalog.BadCatalog):
            catalog.load(str(tmp_path / 'absent.json'))

    def test_a_document_with_no_packs_list(self, tmp_path) -> None:
        path = tmp_path / 'packs.json'
        path.write_text(json.dumps({'namespace': 'glisteel'}), encoding='utf-8')
        with pytest.raises(catalog.BadCatalog):
            catalog.load(str(path))

    def test_an_entry_that_is_not_an_object(self, tmp_path) -> None:
        path = tmp_path / 'packs.json'
        path.write_text(json.dumps({'namespace': 'glisteel', 'packs': ['x']}),
                        encoding='utf-8')
        with pytest.raises(catalog.BadCatalog):
            catalog.load(str(path))


class TestNamespacing:
    """A registry may only declare keys under its own namespace.

    An extra registry is somebody else's file naming URLs this application will
    fetch. Without this rule it could declare `glisteel/ashdown` and be resolved
    in place of the shipped pack of that name.
    """

    def test_a_key_outside_the_namespace_is_refused(self, tmp_path) -> None:
        path = registry(tmp_path, {'key': 'glisteel/ashdown'},
                        namespace='contrib.someone')
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(path)
        assert 'contrib.someone' in str(raised.value)

    def test_a_key_with_no_namespace_is_refused(self, tmp_path) -> None:
        with pytest.raises(catalog.BadCatalog):
            catalog.load(registry(tmp_path, {'key': 'ashdown'}))

    def test_a_document_with_no_namespace_is_refused(self, tmp_path) -> None:
        path = tmp_path / 'packs.json'
        path.write_text(json.dumps({'packs': [ENTRY]}), encoding='utf-8')
        with pytest.raises(catalog.BadCatalog):
            catalog.load(str(path))

    def test_the_namespace_reads_off_the_key(self, tmp_path) -> None:
        pack, = catalog.load(registry(tmp_path))
        assert pack.namespace == 'glisteel'


class TestABasePack:
    """What the application cannot start without."""

    def test_it_has_to_carry_a_digest(self, tmp_path) -> None:
        """Ours to publish, so the bytes are knowable, so they are checked."""
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(registry(tmp_path, {'base': True}))
        assert 'sha256' in str(raised.value)

    def test_it_may_not_be_one_of_a_family(self, tmp_path) -> None:
        """A family is a choice among alternatives; the floor is not a choice."""
        with pytest.raises(catalog.BadCatalog):
            catalog.load(registry(tmp_path, {'base': True, 'sha256': '00' * 32,
                                             'family': 'glisteel'}))

    def test_one_that_declares_both_is_accepted(self, tmp_path) -> None:
        pack, = catalog.load(registry(tmp_path, {'base': True,
                                                 'sha256': 'ab' * 32}))
        assert pack.base and pack.sha256 == 'ab' * 32

    def test_a_digest_that_is_not_one_is_refused(self, tmp_path) -> None:
        for bad in ('abc', 'zz' * 32, 'AB' * 31):
            with pytest.raises(catalog.BadCatalog):
                catalog.load(registry(tmp_path, {'sha256': bad}))

    def test_a_digest_is_compared_without_case(self, tmp_path) -> None:
        pack, = catalog.load(registry(tmp_path, {'sha256': 'AB' * 32}))
        assert pack.sha256 == 'ab' * 32


class TestMergingRegistries:
    def test_an_extra_registry_adds_to_the_shipped_one(self, tmp_path) -> None:
        shipped = catalog.load(registry(tmp_path, {'key': 'glisteel/ashdown'}))
        extra = catalog.load(registry(
            tmp_path, {'key': 'contrib.someone/hillclimb'},
            namespace='contrib.someone', name='extra.json'))
        merged = catalog.merge(shipped, extra)
        assert [pack.key for pack in merged] == [
            'glisteel/ashdown', 'contrib.someone/hillclimb']

    def test_two_registries_declaring_one_key_is_refused(self, tmp_path) -> None:
        one = catalog.load(registry(tmp_path, {'key': 'glisteel/ashdown'}))
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.merge(one, one)
        assert 'glisteel/ashdown' in str(raised.value)

    def test_a_key_names_at_most_one_pack(self, tmp_path) -> None:
        packs = catalog.load(registry(tmp_path, {'key': 'glisteel/one'},
                                      {'key': 'glisteel/two'}))
        assert catalog.pack_for_key('glisteel/two', packs).title == 'Ashdown'
        assert catalog.pack_for_key('glisteel/absent', packs) is None

    def test_one_registry_repeating_a_key_is_refused(self, tmp_path) -> None:
        with pytest.raises(catalog.BadCatalog):
            catalog.load(registry(tmp_path, {'key': 'glisteel/one'},
                                  {'key': 'glisteel/one'}))


class TestWhatAPackNeeds:
    def test_a_needed_pack_nothing_declares_is_refused(self, tmp_path) -> None:
        """A pack incomplete without one that does not exist renders grey."""
        packs = catalog.load(registry(
            tmp_path, {'key': 'glisteel/ashdown',
                       'needs': ['glisteel/absent']}))
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.merge(packs)
        assert 'glisteel/absent' in str(raised.value)

    def test_one_that_is_declared_resolves(self, tmp_path) -> None:
        packs = catalog.load(registry(
            tmp_path, {'key': 'glisteel/ashdown',
                       'needs': ['glisteel/forest-art']},
            {'key': 'glisteel/forest-art'}))
        merged = catalog.merge(packs)
        wanted = catalog.with_needed(
            catalog.pack_for_key('glisteel/ashdown', merged), merged)
        assert [pack.key for pack in wanted] == [
            'glisteel/ashdown', 'glisteel/forest-art']

    def test_a_cycle_does_not_hang(self, tmp_path) -> None:
        packs = catalog.merge(catalog.load(registry(
            tmp_path,
            {'key': 'glisteel/one', 'needs': ['glisteel/two']},
            {'key': 'glisteel/two', 'needs': ['glisteel/one']})))
        wanted = catalog.with_needed(packs[0], packs)
        assert sorted(pack.key for pack in wanted) == [
            'glisteel/one', 'glisteel/two']


class TestWhatAPackSays:
    def test_the_size_is_shown_as_the_user_reads_it(self, tmp_path) -> None:
        pack, = catalog.load(registry(tmp_path,
                                      {'approximate_bytes': 31_457_280}))
        assert pack.human_size() == '31 MB'


class TestADocumentThatIsMalformedInOtherWays:
    """The rest of the refusals, each a typo somebody would otherwise chase."""

    def test_a_top_level_that_is_not_an_object(self, tmp_path) -> None:
        path = tmp_path / 'packs.json'
        path.write_text(json.dumps([ENTRY]), encoding='utf-8')
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(str(path))
        assert 'not a content registry' in str(raised.value)

    def test_a_namespace_that_is_not_a_name(self, tmp_path) -> None:
        for bad in ['', 'has space', '../x', 42]:
            path = tmp_path / 'packs.json'
            path.write_text(json.dumps({'namespace': bad, 'packs': []}),
                            encoding='utf-8')
            with pytest.raises(catalog.BadCatalog):
                catalog.load(str(path))

    def test_a_preview_that_is_not_a_path(self, tmp_path) -> None:
        with pytest.raises(catalog.BadCatalog):
            catalog.load(registry(tmp_path, {'preview': 42}))

    @pytest.mark.parametrize('marker', ['/absolute', '../outside', 42])
    def test_a_marker_that_is_not_inside_the_pack(self, tmp_path, marker) -> None:
        """The marker is joined against the pack's own directory to test it."""
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(registry(tmp_path, {'marker': marker}))
        assert 'marker' in str(raised.value)

    def test_a_size_that_is_not_a_number(self, tmp_path) -> None:
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(registry(tmp_path, {'approximate_bytes': 'large'}))
        assert 'size' in str(raised.value)


class TestWhatIsWorthOffering:
    """A registry names content a chooser puts in front of somebody, and
    content that arrives with it.

    The art four tracks share is the second kind: it is fetched by choosing a
    track, and a line of its own in a download screen offers a player something
    they cannot use on its own -- and one that never reads as installed, since
    a needed pack lands under each pack that needs it.
    """

    def packs(self, tmp_path):
        return catalog.merge(catalog.load(registry(
            tmp_path,
            {'key': 'glisteel/cars', 'directory': 'cars', 'base': True,
             'sha256': 'ab' * 32, 'marker': 'cars/hero.glb'},
            {'key': 'glisteel/forest-art', 'directory': 'forest-art'},
            {'key': 'glisteel/ashdown', 'needs': ['glisteel/forest-art']},
            {'key': 'glisteel/beacon', 'directory': 'beacon',
             'needs': ['glisteel/forest-art']})))

    def test_what_another_pack_needs_is_not_offered_on_its_own(self,
                                                               tmp_path) -> None:
        assert [one.key for one in catalog.offered(self.packs(tmp_path))] == [
            'glisteel/cars', 'glisteel/ashdown', 'glisteel/beacon']

    def test_a_registry_where_nothing_needs_anything_offers_all_of_it(
            self, tmp_path) -> None:
        packs = catalog.merge(catalog.load(registry(tmp_path)))
        assert catalog.offered(packs) == packs
