"""A registry and the pictures that go with it.

A picker showing packs that are not downloaded yet has nothing to show them
*with*: the pack's own art is inside the archive, which is the thing being
chosen whether to fetch. So a registry carries small preview images alongside
its JSON, and a registry handed around as one file is a zip of both.
"""

import json
import os
import zipfile

import pytest

from OpenGLContext.contentpacks import archive, catalog, fetch
from OpenGLContext.contentpacks.store import ContentStore
from OpenGLContext.loaders import resolver

#: The smallest thing a decoder will agree is a PNG.
PNG = bytes.fromhex(
    '89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4'
    '890000000a49444154789c6360000002000100' '05fe02fe' 'a7e9b7b8'
    '0000000049454e44ae426082')

ENTRY = {
    'key': 'glisteel/ashdown',
    'title': 'Ashdown',
    'url': 'https://example.invalid/ashdown.tar.gz',
    'directory': 'ashdown',
    'archive': 'tar',
    'approximate_bytes': 32 * 1024 * 1024,
    'copyright': 'Generated by OpenGLContext (BSD-3-Clause)',
    'marker': 'tileset.json',
}


def document(*entries, namespace='glisteel'):
    return {'namespace': namespace,
            'packs': [dict(ENTRY, **entry) for entry in (entries or [{}])]}


def loose(tmp_path, *entries, pictures=(), namespace='glisteel'):
    """A registry as a plain .json, with its pictures beside it."""
    where = tmp_path / 'shipped'
    where.mkdir(exist_ok=True)
    (where / catalog.MANIFEST).write_text(
        json.dumps(document(*entries, namespace=namespace)), encoding='utf-8')
    for name in pictures:
        path = where / name
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_bytes(PNG)
    return str(where / catalog.MANIFEST)


def bundle(tmp_path, *entries, pictures=(), namespace='glisteel',
           manifest=None, name='registry.zip'):
    """A registry as one zip: the JSON and the pictures together."""
    path = tmp_path / name
    with zipfile.ZipFile(path, 'w') as handle:
        handle.writestr(manifest or catalog.MANIFEST,
                        json.dumps(document(*entries, namespace=namespace)))
        for picture in pictures:
            handle.writestr(picture, PNG)
    return str(path)


class TestAPreviewBesideTheRegistry:
    def test_it_resolves_to_a_file_the_picker_can_open(self, tmp_path) -> None:
        path = loose(tmp_path, {'preview': 'previews/ashdown.png'},
                     pictures=['previews/ashdown.png'])
        pack, = catalog.load(path)
        assert os.path.isfile(pack.preview)
        assert open(pack.preview, 'rb').read() == PNG

    def test_a_pack_with_none_says_so(self, tmp_path) -> None:
        pack, = catalog.load(loose(tmp_path))
        assert pack.preview == ''

    def test_one_named_but_not_there_gives_no_preview(self, tmp_path) -> None:
        """A plate is missing; a chooser that will not open is worse."""
        pack, = catalog.load(loose(tmp_path, {'preview': 'previews/gone.png'}))
        assert pack.preview == ''

    @pytest.mark.parametrize('name', ['a.png', 'a.jpg', 'a.jpeg', 'A.PNG'])
    def test_the_formats_a_picker_can_decode(self, tmp_path, name) -> None:
        pack, = catalog.load(loose(tmp_path, {'preview': name},
                                   pictures=[name]))
        assert pack.preview.endswith(name)

    @pytest.mark.parametrize('name', ['a.svg', 'a.tga', 'a.exe', 'a'])
    def test_anything_else_is_refused(self, tmp_path, name) -> None:
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load(loose(tmp_path, {'preview': name}, pictures=[name]))
        assert 'preview' in str(raised.value)

    @pytest.mark.parametrize('name', ['../outside.png', '/etc/x.png',
                                      'a/../../outside.png'])
    def test_one_that_climbs_out_of_the_registry_is_refused(self, tmp_path,
                                                            name) -> None:
        """A registry may name a picture within itself and nowhere else."""
        with pytest.raises(catalog.BadCatalog):
            catalog.load(loose(tmp_path, {'preview': name}))


class TestARegistryThatIsOneFile:
    def test_the_json_and_the_pictures_arrive_together(self, tmp_path) -> None:
        path = bundle(tmp_path, {'preview': 'previews/ashdown.png'},
                      pictures=['previews/ashdown.png'])
        packs = catalog.load_bundle(path, str(tmp_path / 'unpacked'))
        assert [pack.key for pack in packs] == ['glisteel/ashdown']
        assert os.path.isfile(packs[0].preview)
        assert open(packs[0].preview, 'rb').read() == PNG

    def test_it_is_the_same_registry_either_way(self, tmp_path) -> None:
        entry = {'preview': 'previews/ashdown.png'}
        one, = catalog.load(loose(tmp_path, entry,
                                  pictures=['previews/ashdown.png']))
        two, = catalog.load_bundle(
            bundle(tmp_path, entry, pictures=['previews/ashdown.png']),
            str(tmp_path / 'unpacked'))
        assert one.key == two.key and one.approximate_bytes == \
            two.approximate_bytes
        assert os.path.basename(one.preview) == os.path.basename(two.preview)

    def test_one_with_no_manifest_in_it_is_refused(self, tmp_path) -> None:
        path = bundle(tmp_path, manifest='catalogue.json')
        with pytest.raises(catalog.BadCatalog) as raised:
            catalog.load_bundle(path, str(tmp_path / 'unpacked'))
        assert catalog.MANIFEST in str(raised.value)

    def test_an_entry_that_would_escape_is_refused(self, tmp_path) -> None:
        """The bundle goes through the same extractor as a content pack."""
        path = tmp_path / 'bad.zip'
        with zipfile.ZipFile(path, 'w') as handle:
            handle.writestr(catalog.MANIFEST, json.dumps(document()))
            handle.writestr('../escaped.png', PNG)
        with pytest.raises(archive.UnsafeArchive):
            catalog.load_bundle(str(path), str(tmp_path / 'unpacked'))

    def test_a_file_that_is_not_a_zip_is_refused(self, tmp_path) -> None:
        path = tmp_path / 'a.zip'
        path.write_bytes(b'not a zip')
        with pytest.raises(archive.UnreadableArchive):
            catalog.load_bundle(str(path), str(tmp_path / 'unpacked'))


class TestWhatTheStoreReads:
    """Registries a build did not ship, in one call, whichever form they take."""

    @pytest.fixture
    def store(self, tmp_path):
        return ContentStore('glisteel', root=str(tmp_path / 'content'),
                            search=[])

    def added(self, store, name, path):
        where = os.path.join(store.root, 'registries')
        os.makedirs(where, exist_ok=True)
        with open(path, 'rb') as source, \
                open(os.path.join(where, name), 'wb') as target:
            target.write(source.read())

    def test_both_a_json_and_a_zip_are_found(self, store, tmp_path) -> None:
        self.added(store, 'one.json',
                   loose(tmp_path, {'key': 'glisteel/one'}))
        self.added(store, 'two.zip',
                   bundle(tmp_path, {'key': 'contrib.x/two'},
                          namespace='contrib.x'))
        assert len(store.registries()) == 2
        packs = store.load_registries()
        assert sorted(pack.key for pack in packs) == ['contrib.x/two',
                                                      'glisteel/one']

    def test_a_bundle_unpacks_under_the_store(self, store, tmp_path) -> None:
        self.added(store, 'two.zip',
                   bundle(tmp_path, {'key': 'contrib.x/two',
                                     'preview': 'p.png'},
                          pictures=['p.png'], namespace='contrib.x'))
        pack, = store.load_registries()
        assert pack.preview.startswith(store.root)
        assert os.path.isfile(pack.preview)

    def test_a_registry_that_will_not_load_names_itself(self, store) -> None:
        """Refused loudly: one silently dropped is one nobody can see missing."""
        where = os.path.join(store.root, 'registries')
        os.makedirs(where, exist_ok=True)
        with open(os.path.join(where, 'broken.json'), 'w') as handle:
            handle.write('{')
        with pytest.raises(catalog.BadCatalog) as raised:
            store.load_registries()
        assert 'broken.json' in str(raised.value)

    def test_none_added_is_no_packs_and_no_complaint(self, store) -> None:
        assert store.load_registries() == []


class TestARefreshedBundle:
    """A second bundle into the same place replaces the first as a whole."""

    def test_one_with_no_manifest_does_not_load_the_old_one(self, tmp_path):
        into = str(tmp_path / 'unpacked')
        catalog.load_bundle(bundle(tmp_path, name='one.zip'), into)
        empty = tmp_path / 'two.zip'
        with zipfile.ZipFile(empty, 'w') as handle:
            handle.writestr('readme.txt', 'no registry here')
        with pytest.raises(catalog.BadCatalog):
            catalog.load_bundle(str(empty), into)

    def test_a_picture_it_dropped_is_not_shown(self, tmp_path):
        into = str(tmp_path / 'unpacked')
        catalog.load_bundle(bundle(tmp_path, {'preview': 'p.png'},
                                   pictures=['p.png'], name='one.zip'), into)
        packs = catalog.load_bundle(bundle(tmp_path, {'preview': 'p.png'},
                                           name='two.zip'), into)
        assert packs[0].preview == ''

    def test_one_that_fails_leaves_the_last_good_one(self, tmp_path):
        into = str(tmp_path / 'unpacked')
        catalog.load_bundle(bundle(tmp_path, name='one.zip'), into)
        bad = bundle(tmp_path, {'key': 'someone/else'}, name='bad.zip')
        with pytest.raises(catalog.BadCatalog):
            catalog.load_bundle(bad, into)
        assert [pack.key for pack in catalog.load(
            os.path.join(into, catalog.MANIFEST))] == ['glisteel/ashdown']

    def test_the_same_bundle_is_not_unpacked_twice(self, tmp_path,
                                                   monkeypatch):
        """``load_registries`` reads every bundle on every start."""
        into = str(tmp_path / 'unpacked')
        path = bundle(tmp_path)
        catalog.load_bundle(path, into)
        calls = []
        real = archive.extract
        monkeypatch.setattr(archive, 'extract',
                            lambda *a, **k: calls.append(1) or real(*a, **k))
        assert catalog.load_bundle(path, into)
        assert calls == []

    def test_it_unpacks_under_the_cap_it_is_fetched_under(self):
        assert fetch.REGISTRY_LIMIT == catalog.REGISTRY_LIMIT


class TestARegistryThatFailsToLoad:
    """A fetched bundle that does not validate is not kept."""

    def test_the_store_still_loads_its_other_registries(self, tmp_path,
                                                        monkeypatch):
        store = ContentStore('glisteel', root=str(tmp_path / 'store'),
                             search=[])
        bad = bundle(tmp_path, {'key': 'glisteel/x', 'copyright': ''},
                     name='bad.zip')
        monkeypatch.setattr(resolver, 'fetch_to_cache',
                            lambda url, **_named: bad)
        with pytest.raises(catalog.BadCatalog):
            fetch.fetch_registry('https://example.invalid/bad.zip', store)
        assert store.registries() == []
        assert store.load_registries() == []
        unpacked = os.path.join(store.root, 'registries', '.unpacked')
        assert not os.path.isdir(unpacked) or not [
            name for name in os.listdir(unpacked) if not name.endswith('.lock')]
