# -*- coding: utf-8 -*-
"""Font atlas index for shader-based text rendering.

Font: DejaVu Sans Mono
License: DejaVu Fonts License (permissive, allows embedding)
Homepage: https://dejavu-fonts.github.io/

DejaVu fonts are based on Bitstream Vera fonts. Bitstream Vera fonts
are released to the public domain. DejaVu changes are in public domain.
Glyphs imported from other sources are under compatible permissive licenses.

The full license text is available at:
https://dejavu-fonts.github.io/License.html

This license explicitly permits:
- Embedding in documents and software
- Redistribution with or without modification
- Commercial and non-commercial use

"""
# Generated by scripts/generate_font_atlas.py

import importlib

# Font information
FONT_NAME = 'DejaVu Sans Mono'

# Available font sizes
SIZES = [10, 12, 14, 16, 18, 20, 24, 28, 32]

# Character mapping info
FIRST_CHAR = 32
LAST_CHAR = 126
CHARS_PER_ROW = 16


def get_atlas(size):
    """Get the atlas module for the specified size.

    Args:
        size: Font size in pixels

    Returns:
        Module with atlas data, or None if size not available
    """
    if size not in SIZES:
        return None

    module_name = f".font_atlas_{size}"
    try:
        return importlib.import_module(module_name, package=__name__)
    except ImportError:
        return None


def get_closest_atlas(size):
    """Get the atlas module closest to the specified size.

    Args:
        size: Desired font size in pixels

    Returns:
        Tuple of (actual_size, module)
    """
    if not SIZES:
        return None, None

    # Find closest size
    closest = min(SIZES, key=lambda s: abs(s - size))
    return closest, get_atlas(closest)


def get_available_sizes():
    """Return list of available font sizes."""
    return list(SIZES)
