# -*- coding: utf-8 -*-
"""Font atlas resource: DejaVu Sans Mono size 12

Font: DejaVu Sans Mono
License: DejaVu Fonts License (permissive, allows embedding)
Homepage: https://dejavu-fonts.github.io/

DejaVu fonts are based on Bitstream Vera fonts. Bitstream Vera fonts
are released to the public domain. DejaVu changes are in public domain.
Glyphs imported from other sources are under compatible permissive licenses.

The full license text is available at:
https://dejavu-fonts.github.io/License.html

This license explicitly permits:
- Embedding in documents and software
- Redistribution with or without modification
- Commercial and non-commercial use

"""
# Generated by scripts/generate_font_atlas.py

import base64

font_name = 'DejaVu Sans Mono'
font_size = 12
char_width = 10
char_height = 17
atlas_width = 160
atlas_height = 102
first_char = 32
last_char = 126
chars_per_row = 16
baseline = 13
ascent = 12
descent = 3

# PNG image data (base64 encoded)
_png_base64 = (
    'iVBORw0KGgoAAAANSUhEUgAAAKAAAABmCAYAAABMfpqEAAAXsElEQVR42u1dd7xVxbX+1uVe6UqT'
    'oqDRAAYRBESxELElomKi2KJGNMYoEZQXFUVExZbYXiKK3ajBhrE8EwsaEXtEsaH4KNcWOleadAT5'
    '3h/7O8/Ndna555x7uMJ8v9/93XP2Xmdm75k1a9bMfLMG8PDw8PDw8PD44YPktiSnkayXIPMsyQN9'
    'aRVW0GtI7p1wv5wk9XkiyQOKlO+1JJvE3NuD5KckZ5P8WQZFeYnkWgb4UYr8fJJtMzzff5McliLz'
    'U5JvZXzfxzcjnWlGcgnJdrVKAaUMM0LWYT+HTCeSr5H8huRUksc4ZMaR7E2yI8l3Up7/CpKPJlmq'
    '6iogybokF2aQM5IzSXZJkHmU5O4kHyfZkuRjJLf9gSvgZSTHhK+V1ZJn6wfgGZKNAOwGwGUdbgXw'
    'CoBbAJwC4MiYtNYDIAALvXgbh1w9AJVmtqaI79ELwFIzm50kZGYE8CqAwxPEBgM4B8A+AO4EMNLM'
    'vkqo3C+zWOhNqHz1AQwCcEOxElxNsleBaRzFePSMyE4huW/GLnguyUNJHkHyCZKDHbL7kpxDcpsi'
    'FvIgks9mlB1O8uGE+y1I3q13eZJk55T0arsCnk3yuWImuJRk1yKl9TnJpuoWh8TIDCD5Ack3SP6M'
    'ZJ2Erv9kks+QHEKygas1Kp2Zqlwr0ntcQnJsRtlzkiqkul1wbVZAkmUyDN9zwwrpgpcD+LoID7cj'
    'gK/NbAmAPupmXd3WGAC/APAVgNMATCLZIurcA/gHgAoAFwI4A8AXJI+OJDcEwOcAOgFoC2C4fj+b'
    'ZCFlshRA44yyW0s+rps+wcwm63OVmR0X7YJJjsh1FwB2BDBLX58psE7mh3qi9kXQwWMBLDazV2pb'
    'y1gf0/1emzYKJvkQyaGRe41z1ozkfSSPJtmO5EcRuftJDtLnliQrSf6e5KsFvs/+JD/NKPsgyYuK'
    'WJa12QJOInms615ZAYkmjoKzwMzKAfwNwFEADgLwhAUYFlNhvQFsBaANgN0BzIukt1wOPjQI2QDg'
    'WwDR7volAH8guaes+HUAbgMwqsCyfhtAkyyjYFn7cSVWhCZq4IOLlF57pferBJmDADQB8GRJ5wGr'
    '4Rt8KZ/sJpIDUqzLy5q3m0fyuiTfjeQuJD8h+ZWrgEgOJfkfkl+T/AfJYSTfJVle4DvdmGEesE/W'
    'ecBiWkCSPUiuSxvQFFkBnyc5cHOZy0yciK4lz5dbCamfIPOsLMOmmIf7Swnz60JyQda5Vq+AHh4e'
    'Hh4eHh4eHh4eHh4eHjUPkq1I/ksTzB9rlcAld1NoyeyOhPSOIzmZ5HKSr5LcPUbuIJL/ltxrcXIh'
    '+T1IfktyRMz9iZFlvQdj5OqSHE1ykSa2D3PIdItZKuzrkO1O8i2Sq0hOd6w/5+R6i1SxmuT7JHts'
    '5nq1vYgUS0U6OTZO8DExL1qQvFSrBOUJCY+OU0BV7pOqlEYk/6iZenPIjpVSNdTi+hcJeZZJSSen'
    'KGC/DAVzE8k3SXbQ5PGVGX7TjeRiknUd9z7R6kwDkv2lYC0c5TKP5GCVy1BVSp3NWAEv0Jp8I1Gy'
    'VpKsiArV1xLXHvq+FckVJPfPRwEdsm1lOdpksMKMox2RPFOV/FQhCkiyQhZ3t2oW5i0kb3dcNxEr'
    'uoeurXRwGrvKQlrodyviepsaVIodSF5F8q48fz+E5J3Vtd4k9yG5LGzYcmSEnRAs8n8CAGb2DYDP'
    'AOxSpHfeA8BcAFUJD9cAAWN2KoBFjvvNAfwXgGsy5DdGFftyzLrnzgjICkerQL4geVpK4W0F4CQE'
    '5ImNIALEcwCOV2P+JYAFAKZERRGwtaPoEJNn6lprVjmSdUj2E1XrHQCNAOS7LDcWwJcAxorp8luS'
    'DVOesaPK7vdmtj56c0+14EaiJvUQYfMPhVpAbUT5LLbvD2SeUgFWJfiKd5M8MyQ/IiXfFiTvUN4V'
    'jvddR/IekluTPES+b8eE9I4nOT3h/k7qTinr+jOHTD1x7c6WyzFUe1zOqEkFJHm4GtmzJI/5Xhf4'
    'ndyIGJ/3mYS8fyrq2xyS58fIGMlZJPvHJbKrMqoXujaZ5O8KUUBZg9dJXp5BURuQPEMv0jRyryfJ'
    'D3O+UhYFDPlc66JKTbKz3rdD6NpbJE9PSGscyUti7tWT8p2hd/6pfMWfOGT7kPxIXfEDJN8meXwN'
    'd7k5BXxG/mlFEdPuTfLeFAXcTuVdnqQoa3N9ejF8QFHjnyZ5WzVfaE50lElyYEzLHJvWbUoBu0Su'
    'N5TFbx/xHX+TMJJbR3KHmPvdlV5ZRKEHpjxfQ40OO5bA76tD8khZwXkk/0yyUz4WUL76MI3231XD'
    'a1joAz6mv+ba2zAzqaWkjIJNrfvhJIq7RpU3ktxZlfEbdYU7pjyr0wJqRHuDnOymJG9WIVU4ZJ8L'
    'dcEHa9TaPia/4SRfSnieprJoZ8ka9tYgZH+H7LnaYtqa5JiUdLN2wdUimqp8ri5wEHJX1kFI6D0a'
    'pY1AX5QlnEJyrxi5wY4WMjBm1Ju2062OKmSaKuwDkkdmeKE4BSwjebGmfL4WGXKXmDTaaWP6GvmJ'
    'JyfkN4PkqSnPdIS61tXq7uI2V3WWe7NSO/a2LYICFpVoWgPWN10BPX7Qc20lJZp6eHh4eHh4eHh4'
    'eHh4eHh4eGwZ0MoBSV4cc79eaPJ5vQgOpyWkd6FWXpaSvD26kVlrwSS5QYv590a5diHZaY4JcFdk'
    'hAcdclc75BromRYq75HR1Z3c80WuvRETFm6KI996Me/yYUjmHsf9jfLV2veEGNnxJC9IqdeRyquP'
    'vm+jhYnoUlyOqHtlJP2BjjR3Fh9gjepmow354bXLpuJ4VWkh/ZaEpbh+AD5EfJDIHDoBqAvgdAB3'
    'uFYlRHgYBOB4ANsD+AhAXMiPCgD7A2gGICkC1Im2MeLWjEdF5FwEh1sQBM3cB0BXACsA5L12a2a7'
    'mZkhiFmzp/JdEyPbTbK3ZjAKdQA8AmAxgLMKsC9fAMixuY8EMCdGbj2AARnItA8ioNhtB2A0gCdI'
    'br2RAkrR/gVgCYKgPx30g7i1xSMAXAFgj7SwsWb2rZm9joAf51oquhjApWY20cxWmtntcWG8lNYM'
    'BBFSuxUamyZDpW4PYACAM82sUmHSbjSzabWwY7oLQWi4k8zs2wLSeRlALoD6MQCeipFbKyPUL6H8'
    '2qrhjjSzxWY2GsBKAH2jFvBUAJ+b2TAzm2dmixCEhz3ekWhHAO0APK8HODytZZI8BEBLyYfvNUVA'
    'hn2zmlZkOYBKAN1ruFK7IohdOLWWu0TXS2mOFpm4EKwD8LFiLf4IwP+mKP2ZCfd3AbDazOaGrlUi'
    'RHQuC5na0WKGPE1yGYA/AWjuSPRIAG+p25iQ1AJketcDeAHAVWb2eeR+K/1fnEdBrQAQF173kYiP'
    'FUe9HxKRa+94vkWhil4quWExisBQwMj9SqiDR6iBdylSev+jbv+FFLnnAXRKiHrfAMDqyLXVCNjY'
    'GyngjgBmADgbwCwArQHcoQRc/t8EfZ4A4NAEX7ETgth8XQGc7mBFL9D/ZnkUUiMAyzL6gFMy+oCf'
    'Op6vacjyNgHwaIJl/n9U16pnMXQJ9w4BcDWAe10bpvLAOADtE7rf3PtuAHA/gki0LqwCEI0SVl/G'
    'YyMFJIByfBfUkfofbeHbqGVfpVb+L/kdfZIe0sw+QbBnom/k3hIAM6trLUTr6QDggxq2LB8DaBpm'
    'Tm8iNJZ/HlfG8wDcCOAbACMLzczMVplZAzObmEH8r3LhXIORGQDqRzajtQcwPaqAlTLft6rfr9LI'
    'dFUkwb7qLuuEWvqzSaNhcfR2RhABtdIhch2AK0nuLWLlmblpgBh/sgOAMfInJ9Zkreu4hUc0gt9J'
    'DXC7Evh0RymIeUsdoHNg1H92POt6AL8DcF5ud2MpYGZz4mYuzGwWgqixl2uW5Ww1pheiCvg4gEsA'
    'LDezfmbW2MwGmFlHh6/xlExvDk8k+IFT5dS+juBcjJscMrfLmX0cwH80sHg7wUF+A0FY3X6hcLxp'
    'PuAFBZTx2QgCmr+v//MAPFCAck1R71EHQaB11zzgeLkvHwOYpC7x7xmU4R25TvfGuEU3RMqlWKcw'
    '3Yng3BUXfi3jNh9BcPhjzezraKEYyX+Kkr/r5rxR2qP2DuUrtBdkuma/p2kvrIeHh4eHh4eHh4eH'
    'h4eHh0ctAcm+cZv/80xvTRw/stgI8wGnhUifcxXWwhXSIpFgKJmfhAokFwn00JiX3UPpLSf5nktO'
    'EQ5cWBGR+94OfE38/joidy3JpyLXLiT5cuTaomiECM2Zro0ENtpLYd62D10bEyWGivAZzeM6ki86'
    '3nmF432TzpZ7T4tT7zrS6ioybaYTi8ysHjKcm6djcb8hOaoYrWgayV+pgDsrvMVQh9y/FRekmcJ0'
    'LAkTDCMKWE+Bj85TgTaJyJVL2c9XbJjdoke6x7TOvWPuZVXAPnrusoiSXxiRm0jyuMi1NgqDUR65'
    'fhfJv4UUskoxDcMyDRR86TB9314Nr0vKO2+t352UYAHfTUmjWme2KYLs1Qn3DyE5lWRHhXYeWhQF'
    'DH2/IxpfORTzZbvQtdnR8GJhBQwVPKORQKUw66tzRm+RFLBcsWN66nuFGkg0itYDahztlO5RJHuR'
    'rHTk3Vy0/T0VGSsu0tZpotqbYh7emeGdb006iT2jAh6krRFlhSqgDtJ+P3c4ogzNuKT4OqldcKSL'
    '6YyAePBR5HYqwdCRXl0EbInFCLEghDkIWB4jSbYulc+khfvxCAgSANALwFIz+zgiWglgBwDdAMwG'
    '0EPfKx1pLgIwAsFWgXUIaEoujEHANLoSAeP40hRF2BvAyQAGFvjOExAckN2/COU32cx6iKwBM1tj'
    'ZoeZ2UOFKuAjCPYqjEfAcrkpcj+OYBgXG241gDUALgCwr5kti7zIainBbgAqFZ3/xBLp4Th8Rz0/'
    'GO6ze2dI4boDuDtJAYXXEBBDJ8QRJUTkOE/Kep2ZJYUtLkdA1BguZkmhuAHBSfK1BlEFPNHMysys'
    'jZkNctC74wiGccTQ+ghY1V8C+G1MhXxsZv0RHGp8EYC7CqATbajG9ecB9NZA66AYBQxbwLEIiLtJ'
    'CjgaARtlUNhNcbzzK2roL6W8zwUImD+3F6m+nwDQjOQBtVUB0zAdboLhjITCXoxgc9PgpCj52nD0'
    'HIB3ZWnywUr9D7N5KhBi4Ibym41gB1gfBEHUx8coYDsEHMlKBIHW93IpoPzMtggCqd8H4PoCffKd'
    'Za3OSKCdVbfr/BbAn2uTFSyr5gvMRkACDRMMGwB4MeV3UxHstjrX4bj/VQcb19fmpZ4AJudZwAvU'
    'GAaSbEzycFmtDxO64csAvBt1D5TeMlmqhVKCSfIXKyPv0QQBI3mIma1FEMn/UJL7FlA3twO40cym'
    'F7nO70Owm7ELahOio+AEufbadL1Oc4YHJ8wD1osM25eQbByRPVGRUVcpEulZ+Y6Cdb+bpopWilqW'
    'FJ3/gKRNRpJ5neQf9fmXmveqE5G5zTGvOETzmmUx6a6PmzRWw3RhWr6j4Ij8ZRmmu24qxUR0IQpb'
    'rgDVf4bHpq6Laq2EaA53SdxutlKuhBT64p11vFeZVwMPD4/aZqCSsLcvIQ8PDw8PDw8P7zA21dGb'
    '+xYpvS+LQY5MSH9Njo1RYDqDxPsjyd4FpPNpdRxrMWIOySA3IuVMvntIjkxJo0nI+X+lNithK51I'
    '3m5LUECF+lhVjFWB6ipgEcshVQFDssfWNgXciFSppaz9tyDD3xJAmYOG5VEilOXR4saHYj9PSTrS'
    'FcDhYgbPjJJCI2mepaXAJSLCbuWQ6aFuawXJa1Ks+GMKM1xJ8ug4i4WAXFA31D31dsjtHsr3yhTL'
    'e6AOKlwcxz4OxWFmUhcsdnoOd2Ssm710MPSeeVrTX2t1aw7Jh7TIsIBk9xiLf3GG9/2x4lYv12GO'
    'fYpl+itk0ue7DiJWF/wqyW21Drzadd4uyeNEy99PQbFPjb6wImzN0Anj25AcpYpp60jvZSnxNmIv'
    'VyUsObUluSbhHU2084uV3l8S8v1UrODmOpd3WVJok2L7gGqgM5N8+LQuOKSArVVfx5G8nOSN+b6v'
    '1uVvVvmdImXdupg+yPzowcchBewf+j6B5JkOuedInpeSx66yQOX63tKlCNowtZZkg9C1Ma58Mypg'
    'J5EaEvMNVUi/0PflSeceF1kBH9d2gF8U4gNKAR8K1V8HWeIH8nnfUHk1D12bFv5dPl3wqUpkrcKM'
    'tYI7kioQhDLLYb58rijaIQh7luarLRKVHmIRb4hJaysAy0h+S3IDgoDm2+fZvlplzDeHhaHPa/F9'
    '8m5NoS8CCtuvipDWOv1fr8/ro2OFarxvSwDrtF0hh7kIIvBWXwFFKL0NQSDERgpQuQRBZFUXWkc+'
    'L3DIzEIQqDwJVQCahy1RzLPPQhDTucLM6ojdbWZ2eZ6VsQBAi9z2VJKt8mm0JcAoBPtL+kR38TmU'
    'qzyP9C3P56oCUBHZHdgmrAfVLcz6CML3LpTzPgJAUn8+hGQL7R3uBTft/X4A55PcR9sPT3Y4vdNk'
    'TYfIf3AekKMg6J8A+JMoRzuQvCZloJSEaQiCZg5TdNSLkByreVNhnZktlWG4LWGD1wwAncP7l2sS'
    '6jHeBnBprm6lgK/lpYCq4OsRRCmdpZYxO+EnryCIkno/gN/ldlFF0vw7gD9KZiYCyvuUiMwGdS8D'
    'ZMIXyeS7cIIs6gw95yoAb+VZgFS+x+o9F8uKrCvAZ14h12V3AC/KRxpYpAp/DsDTCDZQue5PBXAP'
    'gOnKt0kJ9PAUBHtq5gAYBleEVI/MytNETPCyEuY5kuTNfh5wy1W6wSQPVdd/EYBxkRjZNZl3PQAH'
    'yBXw2EIVcAeFnlim/21LlO98Wdvnw5EePDw8PDw8PDw8PDw8astg6QSS/yG5MEVudtJASgcWVWXl'
    'GG5phTwiKzVpCyybD3TOXp0CFdBIdlfUi7o1/dx+HnDzQQsA7xd4WjrMjGb2AYKTN1uUsgXNVrzi'
    'KlFxToiR24Xk21pSulnzVd1iZL9Uml+oRb3hkPmxtgGs0J4UF/mxd8zm5kYO2Y2o8aIp/SQis78I'
    'qeFrD0djxKhMOjksxNJIPOjmIoLuq++tSM5zxJfuJYJneejaKNdKhyhWUbROqL+5JHtkrOe2GeRW'
    'ufibNa2Ar4lA+nM9QBuH3NtSqm3EEGaKAn4oPp/FyDwgAmkDkSqvKKQLzqiAZaqwbvpeVyF720fk'
    'niB5SuRaR5KzHPn+XKTZhiSfInlZzPNVkuwbeo55JPdJeadzNQkeF9F2TwVNallEBZwmpnp5KRUw'
    'TCB9LRrnOEQwbKrv9cW7S1LA/in53kfyloRT14uugLp+C8mr9LkfyfcdMkNlobZSg+xO8iSSj8Xk'
    'PUqxk9+K88VIXpGLvU3yYJKfp7zPXupBto25/4zq5IZq1HMWBTxGKzFLHfc6iOm8nOS9+t6e5CWF'
    '+oBRAmmryP2WAL7RSee5ELtpzIaZKfcvQhBQ8h3R6Q8ukdF/DAGHDvrvUqqJCOIV7oOA5nWwvscd'
    'lH0ngnC+9yb4Yg8BOIpkQwAnIgiLHKcEzQA8DGCAmX0VI/YLBOc4/yFOSfPEVfpzWdVeAIYiiBY7'
    'GUGk1+cBvFmoBTw6YgFPj8i0cljA9SkWsGc1nqEvyUUJ94enRZXXRqk++lyhVuyygLluuKv2Bbd3'
    'yNSXv3e1CAn/0D6X/RyydUi+Kb94boq/Nonkb7QJa7eE0ejTJC/KWHaLa8AH7FjqUXCOQJqLVPpC'
    'ZIS0AMB7AC4MsUMKGkkrEOJB2sfRDAEFPA7zAHRP2dRSCeAYDVDORwybV4yWJwHcDGCmmX3qkFkN'
    '4DMAx6uVlyMIqP6eI8nhAJaZ2bkI4kTfF+f3ygreAGC2mU2JkblQz5411O/KIs9qlOG7kMcl8wGv'
    'kM80My5avTbqvKPNOn/KMArumZLv7iRfUnpTSP48QbaxZFcnjIJ7yNH/WrvZnD6gZPsoneEJeY4m'
    '+U99voTkpBg/rSo3Mlbwzkkkz4lJs7V6jksS8v2wmqPg3DxgWaEWUHVSknnA6IP1zON3sQroEVtm'
    'DTXt9OMipnmiDEcxVkIW5gZoXgE3P+UzWeY3NlH+s0vFacyCcq8SJUcVgr0lJ2+KzM2sra8CDw/h'
    '/wB2rFEKmmt8TwAAAABJRU5ErkJggg=='
)

def get_png_data():
    """Return the raw PNG data bytes."""
    return base64.b64decode(_png_base64)

def get_image():
    """Return a PIL Image object (requires Pillow)."""
    import io
    from PIL import Image
    return Image.open(io.BytesIO(get_png_data()))
