# -*- coding: utf-8 -*-
"""Font atlas resource: DejaVu Sans Mono size 18

Font: DejaVu Sans Mono
License: DejaVu Fonts License (permissive, allows embedding)
Homepage: https://dejavu-fonts.github.io/

DejaVu fonts are based on Bitstream Vera fonts. Bitstream Vera fonts
are released to the public domain. DejaVu changes are in public domain.
Glyphs imported from other sources are under compatible permissive licenses.

The full license text is available at:
https://dejavu-fonts.github.io/License.html

This license explicitly permits:
- Embedding in documents and software
- Redistribution with or without modification
- Commercial and non-commercial use

"""
# Generated by scripts/generate_font_atlas.py

import base64

font_name = 'DejaVu Sans Mono'
font_size = 18
char_width = 13
char_height = 24
atlas_width = 208
atlas_height = 144
first_char = 32
last_char = 126
chars_per_row = 16
baseline = 18
ascent = 17
descent = 5

# PNG image data (base64 encoded)
_png_base64 = (
    'iVBORw0KGgoAAAANSUhEUgAAANAAAACQCAYAAAB5/OUYAAAl90lEQVR42u1dZ7gVRbZd+xIkSlYR'
    'BAliwIAggmEcVAwoiFmfoIhxzHkM4xjHjBGfoigmjCOKiICgGEFUVHgmQMyAIjkKEtb70au1aTud'
    'e8/hnou1vu9+53Z17a7Qtat27a5aBTg4ODg4ODg4ODg4ODgULUheR3Km/i8huYDkJRnkJpJsuAHV'
    'QzWS35G8IUPcoSTfcK2nuF/oZfRwaMaXT5LX6PoZktMzpvM6yef0/w56zu4ZFWiTlDhnkPye5M8k'
    'byRZOWOeapHsT/JHkmuUp6EZZXsr/vY51vcVJBeRrJch7k4k12Z5NyG5zUjOda379/o4W++qix9W'
    'UsEKUAlAJwDjFLQHgJUAPoqJvzHJ20hOA9AewCSSg0l2jIjbDcANAI5QGocAuChj1u4BcDaApuuj'
    'TklWB3AJgMfMbEFafDObDOANAFdnePbBJB8mWSsUvjnJESRb/kWVpxKACwFMNLM3K6QCAWgHoCaA'
    '8QEF+sjMVkYUuATAywAuBrAVAAPQGEAvNaYwjgLwhJlNNLPvAdwK4NiM+dobwHQAbQFUMg+HFrAe'
    'jgNQF8ATOcg8CaAdyU4p8T7RsycB6Ky6PFLX0wH8ktLQjlQvvc0GpkNHAWihdvE7KlcQ7V8BYKNA'
    '0Ackg/cpRdolEGcnAHsBeAdAbwAvAOijRn5aVEcNgKHrrB3MNwCqm9kX6/FlzjGzD3OQGRGQfT9h'
    'tJoF4AiSPQDcC6A+gCsBdDezD/7CFtwlAL4GMCQYWLIBF7iRfu80sx/0/2wze87MukbEfx5AL5I7'
    'k2ymCvtvQEkbkjyFZNUI2VsB7EbygvVkSuyepAQxivEzgO8BdMmalP78jmXtX3ju01VTgNvNbG2h'
    'ErlUQ3fPAhbkU5L36v99ld5WMXEbkVxG8h6SlsULR/Ickj+QnEPyDpKbkOxLchTJmSQHkGwUkqlP'
    'chzJGZqoH1Hgl9lC5b6zFLKvkfw1g+PgWZLTSR5Gcq7Msl9UJzX/aiYcydEqf/VCJnKuKm7/Aj1/'
    'Zz1/V10PIjk+ReYYkotJTiO5kOQFJFulyNQm2YvkMCnFA1LWSjHxR8ozWE3exGUkOwTuf0vypjzW'
    'w66qhytLIfusZGsnxOmuuq0V9MKRbKKytgrF78xsqFtBlaed8v/vQifURwl1zvNzV2d4ORMT5Dch'
    'ebJc01PlZn4wrBAasYbIFT2Q5H4y257Ut6bJGsqDMrsr/fa+d0wj3UySmytsYT5NO5IdS/tCST4n'
    '2VoZ46e6sctDgfT9K4jhBWzXT6lTrF9oBTpUhdmumBQo8JyJUoi9pESXhOcWUprKocp7WWbakSSX'
    'ktwycP9Cpd8kENaE5Cyl10H3d8ljfWxZSBMuD/kruAm3vhRIdb2a5D0bgh36Bcm79f8+qriWOcj/'
    'PgeSPTsmJX4JyV+D34xIvkHyosD1BcrHmSHZTiRXqOcanW8ngszS4aWQ/SFLZ1PsCrQe21x/KdCW'
    'cXFKKkhB6gHYBut+QJ1tZt8kyPQg+ahMjBoKrkPyUnnolqY5rgLeqKBnKlhnYxTWT6PR5ppkNwIw'
    'C0ANAMPyWRdmtkb10CnHOmwMYAsAbxbh+x0gpXu0wOkMVzr/yRC3AYCTADxnZt+tj0rIvJSnFM8+'
    'SM9uqutRJF/I2BNS3rGgKbgy4/KfZwImXE+Sy0m2CcW5Pcas/JLkeM2Hque5PvoGHSoZZU6RTKcC'
    't4OcRyDNSUlyYBEp0NWK22599SKFVKDrSX4fMK0Wkrw4RaYKyaOlAD8qbz9rYeVOWUc+kk9rzdmX'
    'JA9OaNAfyWybqwZRX+lTo14+66M6yfkk++cg8wbJT4rUwvhQ9bRbMSiQ6ndOvs3vim7PTkpbTFrB'
    'ynO5FLt+hrilWky6vsxzOXWGFlGezpKidXWa80elfBz+CFrBy+NvZ7gxQ9wXSb5ZpOU4XArUtkjy'
    'U4nk1yQ/dlqzbsV8tCHtB3JwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcFhP0Pqxa/SFe4W2EJye'
    'ItOM5MUkP9Dyhxkp8etq5fIEreeaS/JdkkclyFTTLtFXFX+eFmr2ImkZy9aW5G/K454xcdol7Dm6'
    'LOX5+2m/zUJtY/gvydYxcSek7G+6LEauFcnHxV33K8mvtJi1YUK+Omnx7SLJTCJ5smvtqe1lO22s'
    'nKpFxF9JN6olCQ2KeaEXJMhMCcVNU6C7EhrOLTEy/0iQuT1DZZh4C+YWQoFInqi1Zsyy0SuDArWP'
    'kGmiDicKX5DcKEKmvTrCnN6pAyBOiCg8ECfgs3zOJrknyY20TmmFNnBtHCP3qnrBTko0TYGuFtHH'
    'HlqxXJ/keYEtBw0iZPqI7G8vxa+tvfvzSK4iWSclzbNIfhJQ3jQFOj+Hit6E5BLJ3aA9QdW0BaNf'
    'ji9tBMlJMfcuURrDRCxSVe9sksK7Rcj4HAj3kGxMsgbJ/bUqfXHWrd1/UQV6ieRJquua2qaxXFZM'
    '1SiBa1TZp4fC71T40Rm1dkYpM/xKrvsvxDLKpB2DgZ57F5L9CqBAPpnKgDK+sBZaVHluzP1/K539'
    'QuEXxm0jEZnKIpFMBsPPk0yPImy41UieIIuhThmf1VHtqkccKUyOz3tZ9ba5HxasWL/hjgrJjQrd'
    'LxR+BbAcHvtlWkHqiD7qIADTAPyQEP1eAI+YWS5bmc/UXGYpyXdSGpq/Me+uMpb/DACr4TGIRmEo'
    'gDXKW3ONQG3hMa3OBfBWXHVh3V21QeyQUs+ZN6CVRUZy24jnYRaAx+Dt6l0VuF8a8pJF8PjchgH4'
    'TtZPk1IqTwMAHQF8IfLJPylQY72gH5TQEpLHAPhO9zcvYK/TSspwh5ktTYh3s1hIF8IjPfwQwMFx'
    'ZHdSsnYArsoxS1sBqAOPRnhPAMNInhYTtxmABQAWaLPeMs21nkkaGUP53AhAXwAvmdm8qDhm9qnq'
    'qLneyUoAn6ku9onhyJ6sctwhhp0aoh3zNyOW6/4odQLHaqvFl/AYY18G8Hcza2Nmy8vyfDObBm8b'
    'e094/OlXAvhe7+nA8MicZKYDGAugFoATgveCD6gG4DczI4BKuldZIwMAVC9QJdZXDzEOwLW51A+A'
    'KvqLHKXgkb6fYWbLMj5zDYAH4dEC1wDQCoDv2OgXMw+sqV7zRb2oGgAaADgGwLtZTk9Q3IYABqXE'
    '2yaiI9sSQJuY+LepFz8fwE8AlgF4FcBrgXdeHopTl+StAGYAeFr5OB3AZmbWx8zejlCGCZYNC0Ny'
    'q81smLjKmwK4HMDWAEYCmK6NiZUT8loDwGgALdVZfxQX8X1N4i0UvnVWwodc50DiYvtE9m6tHOQa'
    'iDRxrhh26kTEGUDyyVBY4hwoIb0nEybq78uRMUFzqGqqs9GSuTDD8ydo23lJQpzj9LznSbZWOjuT'
    'fE8OmI4xcnuRHCtzdAHJe+Wdy+TBLJAC+ebYgkIy2abk4RxxYyRy1pG8SHEOS3vgUEVsHgo/QOE3'
    '5lOBSDYVz8C4JKbMlGecrrwdH6GYa1Ns5RU5pHO+ZE6IuDcsiuBD351I8vGUZ7fPuE9/tJwMtWLk'
    '78mhPKdK5txyHIFuE+8ASb6lTwE1MyhdqQkcxQt4nkgyKdbYK1JGoMcVt0bU/WCP57tPDwjFOTB0'
    'Px8V2AbAu5r8HmhmS0pr5sbY8hsF7uUDO+t3TsS9zwKT9ai8MeXZZynOIynxNg09N4xNMtZ9ZXhn'
    'GQHAe+WhQGa20MwuAdAE3lEtUPl/1ueKPfPY1irpzKPnAcwEcLvmkAcBaGVmN5rZ6oRH+C7r39IS'
    '2jHAXLNH6DvQkiwuxYzfgdrL7Hojjag8IPOs3LVtxZjSUIw3c3Lh487gxh6kU8i2lonUXA6VtXIH'
    '107oGYMmXJuACXd+Sk+8LAtfQYCW9wWZcBuJLGRc8LS/GPNzV9Xb1uJHYBaGnlJ64UrF8SYv3F2B'
    'j8XT4nr9XDpqscRSJvI1pfXCZU3w0Zhh8aJSyJDkQxHxn0kZgg+NkJmYEH9UDst50hTozZg01pLs'
    'm/DcITFy3yV1PAFm0xMy5L29luJEYRbJTWPk5kbEX5KFbriUClQmjjd1QH20VCsf34FGkDyktN+B'
    '1L6ycXvLrXid1lqt1DKdM0qpdPlUoBYkb9JX98VqFO9riU+VHCojTYFa6TSGKWqsCzWSdM3w0m+Q'
    'Tf2bRtgnfCLIGBnTOqvFWXtaktuq/r4LrIW7T6yjcTJ761vWMuXrWZLbZkyvNAq0Xjje1uN8LbsC'
    'OTiUsbEVHcebg0NFUqCi4nhzcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcHBwcKjICLDDPJ0Sr19o'
    '7dtKrekaQLJZiuyWWu4+Q2vBviB5bcwq6eAC1KUkPxdBStL6tK4p6/T+EyO3NEFmQkJ63bTWboHW'
    'xE3QeauVY8qzOiJ8G6UzOOLeninlqZWQt1ER8f8REzcub5tpVfVCkh1C95r6GwQztq8ugXz0CN27'
    'Om4/UIBC7PmIvEWu19T92lodPiPQRhP3DgVf6itaeLic5GckL43iHQvINFdm5quyquSgQEHMjjvH'
    'lGQHNbQonJ+iQEHMjzvden0qEMl/Jsh0qegKpC0nn6ludo+QKa0CLSb5bOjeNIUnKdCq4FaGJAXS'
    'QdZvx9TZOuxLYbqjO+ExogyFx9jSCMA5APrA2/MfB39b7rXwSCy6ZKiTvc3M5zVopTQ3gccPEC5Q'
    'FXh75+sCeBQeB0BVePvUrwcQtyFvjdKoCY9R5SkA9QA8ndKTXBuz3/7KBJnPY2Q6R5SnI4Cb4PFN'
    'nKl63hhAJ3g8DqvyYRWY2bt+JgD8W8E9AnlbmiB7YEC2b47WSB38wSPQw8zG59HYeQFAD9/qINkZ'
    'HtHK8ASZ5fD4IE7LmMZhAP4GjyGqPTzOhv3gkcecRnK7PykQybMAHA9gdzMbaGazzWyZmb0B4HAA'
    '3eL23UuBpgEYCI8tpmcOL3m1mX2DPwg16kZE6w6PKedVM+trZl+Z2Soz+9bMrjKzh1PSWG5mE82s'
    'FzxCjZYAupWjxXu+6v48M7vfzOaa2RIz+8DMzjOzcRXYlK8Fj7CjLYDD1X7yiXEAZgM4QtfHK735'
    'CTKrNDCcmmqCefCffYGZfWJmK83sNXV6Jn34Q4G0M/QGAJeZ2XTZf49p49WP6iUXA2gdUWF1AewF'
    'YIRoiN4CcEgOFV6Z5Fbwtjb7FRSGvx/ngTy8gCf0u2c5trN9Nfo8voHNg6vDo6XqCOAYMxtViGRk'
    'SfSWZXIMgMEZ5O6HR912WIa4O+k3rPxjQ/d/H4EOk2YNDjTUnQHsAmA3mXMbw6O7CuNgePRXI3Q9'
    'EsAWUfzOIbwhjrdVGr22lcaPjYjrK+7/5eEFTNFv84Q4V2edmwTQNkamc3hyCo/fYKqZrQyE/5zG'
    'qQ2gUvjh8PjUigUvynwfa2ZDC5jOYAB7AzhFbW94BktnihTizAzP3wzA/Ag6tB/12zisQLsDeN/M'
    'VpBsAeBYmRdTzWxGiu3YU/alz4w5IjQvyoo6AJrEbL31uROW5qHy/UopL17ofJalmFBJ84SPAOwv'
    'UsuCwMy+hEca2Q/AEDPLyrB0H4AuwTlMDKoBiHqmH1Y9rEDNAXyr/7fXaPR+IMNfwWPADA/ZVeGx'
    '9rxuZr8p7jQAX2dQIN+JUFUjzDPwGDP/VeBGXzP0zFycCG+WwokwIaYsNUONYjPVRxLWhB+ukbtY'
    'cDI8VqdfAAyI86jmcRSqkdF88zEUHgnmGSnxViCadNIP+zWsQDXkqQByo4PaB0BtAIeEzIpWAHbK'
    'Qm0rZ8DXKtRsACdGRPtavzvmoeK31u/35dHCROH1C4A2ufA5FMHoAgBrU5T7UVETnw2PafXBAtbj'
    'HepD3shBZrUcXSekdMY/A6gfwRrlf0P8KaxAS6QIAPCpJmq7BkaarWK8Y2mjzCE5FI7y4EVxcPvz'
    'olPzUPe99ftuOTbIsRqBjqogCuS/k8UZ3+V/4bmbe5LsU2RlGagBo3dCHH+u3SViwIDMx3UUaDo8'
    '3mWY2bcyp+4Sr1YTAAMizDeTgiwAUCVkVrTOOg+SF24LfaRsBuCbiGjDZGJ2I/lQgBdtG5JXkTwp'
    'zTukD7FPANgfHrHeyHJ8ifeok7pfjJz1dAbNQeXsRaspvr7D9HG8muiv/BPtPs/hcWfCcy3fTXKL'
    'YtEeM5up9nRqijME8Ej524mtah94vNpU57BOxfXQcoWGvqco4MaeIUqpOSR7B2Q6ymJ7LOZlTNLX'
    '33qh8H4pX8ePi3le58DX5rKsRFgYR7mUYSXC0Bi5pSQ/y7GxXp3AQdc7pjwFXYlAslZC3PEJZYnL'
    '2/GSfS2Cc71pBpreyoH4/kqEU2LycG/CSoSFobB9U6jXSgKElZlWIozQ5OpC304XS35tM2tqZpeb'
    'WSMzGxxhvsWtUBgiF+PBKW1pLTyK31EADjKzp2J6jgnwXOuPKa8r4bmkrwPwcEoayxX3HgA7mtl7'
    'RdATXgvgULlWFyuPbwPYN1TP6zNPS+UEGArvzKVVsvcfKYVXFWb2BIBX4H33OquIRqHXAUxNuL8W'
    'HvVvf7W1VZqHX4k/aJH/pHX7aRQ6GA4ODqWygY+T2Xa3bL/qrlYcHHJTomYk79BWgaUil3/fKZOD'
    'g4ODg4ODg4ODg4ODg4ODg4ODg4ODg4ODw18XWmvoY2KB0giyIJXnqvp1SEW6RixqnEdyZNJW5gj+'
    'rOkk/xVH3hBxkO+cAB9apYR0mpF8hORMfdydqvNBt4uIO4DZcHZIzj8TtGEo3F+UeXMovJfCL4/J'
    '8xO6v3MgbB7JD1IayJJgw1Ad/6iyhxeAlpD8WDLNAuEnKe2rYtJ4Xu94t1D4+RnqrWEZFaASya9J'
    'frQeFbsyybHK/wOFSCBpJfKaqKX2KfxZAzMqUBCPJyjP7BiZGeWoQPVJriY5Nibfs0jODIW9R/Ln'
    'hPdQX2k9HAo/TOG3hMLPjCmLkfxAvXXj0L3d41bSZ1Cgb7QTOWkEGpqhvZ2l53UtQ5udknUEEqkm'
    'SY7R72mFUqBrAr1Ey8Ap3B9GyByhe1+R3Fl7dLqKvHAtyR0SFKhWoMGcoFGFJLeOkOmve0NIttU+'
    'lZaSeyVD2S6LOwG8LAqke+8o7zVC4T7JyIOh8EdVNxvF5KGd5P4ZcW+YRvk2um6ouh5HsiQifmel'
    '9VAofLy2hmyWQ/vors5ijwwmXBYFqi7rY3ShFYhkb9XpZYF3sDKvJ4mHFSg0yszT3p7wno6nJNM9'
    'FH6Jwq9OU6BA+IMKPyZG5jeS1UpZtkIq0KW6d0BMT35IKPwKhbeOyYO/Pb5nzEi8lORIXT+shrBt'
    'QpkekwWxo66P1vMvzqH+GpD8ieR1GedAQzM+198T1a5QCkSyvRh27wqZc8NlITTOyxwoBYZoroQ0'
    '/qxcOAzW6Ddq2/BMePvyGxThvNkfAcOmSFd4e5ZeD4X7+1CaBRp4sEH7dFvT/vQSzH4AcA2AA7WD'
    'ty+A/4ilJg6XwSMy6SfT6ybl4e4cyjgA3v6g6/Jcd/fC2wf1zwLNexrC2z06FMAFgXpcDeBoeDuT'
    'hySZpGUx4UoymHDzSM6LCN9EMuMymHAby75fSnKuaGHDMrtoBJql3bHdwjtdy2sE0v1vSU4KXFfR'
    'pH5kRNwd9KwTdf2ViPKH6Po2mUpVEybDk/WM/8tCTBLg4R6m3wNzqLteejdb5eCFG5rD8/vLutmy'
    'kHOggnvhArhazDpr4O3C6wNv1+jVEXHT+LOSNHuJ0lmkXmImgEPNbFFEzzsRQAd4rKVnw9tBO1sk'
    '+FsXySi0Y4DGqTM81pcowr+vVJ/NpKitATwEj8DSH5m+9WnCIupiNQDfcfKdmWXh0b5L6fYA8FJW'
    'xlDxYdwL4HxRmxUCt8u6ubAiuu2TTDjCIwx5FUBXMxsRoyhJ/FmLMuZjBYBBZhbbm5jZp2Z2lMy4'
    'DgCuANAOwId5JK1gKe+/okawr673C5l3wXKsgMdw2QweoeVSmVON1Qs3R8J2Y80RDwLwATyS9R6p'
    '9renjP428UE51McgAG+Z2UOFaoBm9h2A5wCcRLL+hqBAPqlgiZnVF0t/HPdWGn/WLwlp11b6LQG8'
    'CeBmksdmaQxm9rGZ9YPHKVAbHsVrPrAqMOcLzwEB4LcYubGaZ3QNzH8+V+OIwlQp0G4A3jOz6VKq'
    '3RU+LUZ56knZpsCjXJoMoH/YAxiDtaHfVDez5rCnrId2eCs8mq+zNgQFygU+P1aXULjPnzU+RRko'
    'Gq1j4JFX3Jx0DlEEFoYm3mWFP58LfyjcVL8LYsrhOwu6ktwYHrl6El/ztMAI9LbC3gHwd6UVNwL1'
    '0/0zzOxXeKc8NMcfR5fka/LdGsAtAPqa2dxCN0IzmwRgDIBzKtrO57IqkM+PFcWftQLASxkrcDE8'
    'xpPm8M4jCr/QG0heT7KTXKo1RNr+qKJ8m6f68L+MP6jvODV1ONRNoftxZlwzAKfDYyNK+j7lj0C7'
    'BBTobXjHZpREKRDJvQGcBOAxn2JYv0MAXJTkys5ReSrBOzViUIFOV0gahRohmpm2+BH3HShFJmkl'
    'wkUxMnHfgSqR/FKn0NUP3Xso5VS7xnnywtWSVywKr6XIbq548/SXtCxpf8Vd4Y+4JLcNpBVeOVBN'
    'p7DNi/AQttBz3kjJ35VR3+wi4l2YYQXHgfnywoVkP9JSsJKM8YvSC5fL0LsW3uFX/WWC+ZPs583s'
    '9hyftUamSF0A4fVblwK4SCbhXM1VfoDHB7ermf2UJ1NiKbxzgx6Gx9O9Gh6H9i3yYCXJzgLwCYD6'
    'AEapPEkjEAB84B9xom85cwAsiSjPVfAOGPtn2KSSCXwHvFMHjs9DNexYju3xNni86kfgrwgt5Rme'
    'tMDSYYNvA6VejS0r5JsMi22LbzV2nnrwlbLjn4fnlq3smpRDjlbI7QA6as7n4OBQwUbQrJiS9xHI'
    'wcHBwcHBwcHBwcHBwcHBwcHBwcHBoYDQeZu/hM+BzHMa3bOsSytg+hcr/W0K9PxztZ5utdI5Nk/P'
    'PVDPO7KU8nsmnTGaIDcqivkoIt5ckm/m8Nwwc9JDFVFn1lkpYGZTSO4H4A2Sn5rZ/7puJafGtg9y'
    '4xpwqOD401IbM5tMshuAkSS/NLOxrpoyo5t+9wbwTsqC0vUK7fa1UsgdWKD8/APAP9TxcINRIBXu'
    'fXirih1yw+YAlvv7dRw2fJR5KQ/JfUV4+KPYZT4jeUHSfpiA7L9kOy8Ux9ymKfFbkhwkGuEVJD8X'
    't1i1mPhbaXX4UuWvT4Y8VVW+pohzbTbJB+JYgAJzEwI4DkCNkG1/bIxcK5GiLFPe+madn4ko8GvV'
    '94ikeotggj0lQx38J439NWPbuFHy5+ehndXyuQZJfqj3sjfJw7VPahLJFklzxxzrrYHmabPECPWN'
    '6qVq3rSPZNOExXb9U5wIL0bITIqjaSK5vTbbReHImAr4KYLve2hcI9Vy+ldj0pgYVXlBBYrBsREy'
    'daU04bwNScibn87/Km4QQ8tbgcJOBJK3Kp9nZpBNdSIEFGh+IF+fhyifB+ej3rQtZ3LM+3w+nwrU'
    'hORokj1I1tPOyV00Cq0k2SBBgZaTPE68cG3F40ySJ8Sk9a7uP6n4NUi2ETNoFG/39X4lkdxS+bsg'
    'UIlRjfRU3RtLsoPK00wMoCTZN6U+niG5NEO9XaXnjSTZWgp1jhhE0xRoseqttlg3Z8jjV7tYvHDi'
    'oV5D8uSMaeSiQK+rzfhevH4k64hz/Mt81BvJkyXzsSira5HcRzLMKyVwTGH7KqEuCQrUPxTeXuFP'
    'xCgqdYqDZczDBA3V9SMaRFwjfV0mVe2IkWkRyWfypEDjZYI2CoWPzKBA94bCr1X4TkWgQG8FeMxP'
    'zSGNXBToCl0fqet9dN2P5Px81Jve4zqnagRM53VOvMjHHOhw9dg+oTzxB/dYrQTRMNPpZHhbqKM4'
    '3nwe6VFmltVjswU8gsL5KekG0QZADQCLg2O28rUxgCZ56mOaK29zQuFZdnCG8z8zQ12vL+zhe9YA'
    '7FqgNJbod1nEdbU81dsW8CjMJoXCJ+i3WaIXLgflOR4eg0tOXr60x5byXmYPahlkq+SxIZS2LMtC'
    '12vzUK58YTWAI+ERP55BcpSZDcm3gZPwW7Ke6o35GoFOUQ9wGDwutUpmZoFeKAnhHmpHKdyPEXGn'
    '67dbVhMOHulIiwjv2S4JMj7BYYlFo3OeGsH3AFqGTbiUvFUETDCz4fAIYKYAGEiyaQa5xRrhiwU/'
    'wqOlbhcK7xS4nx8TDh5Dzs9SpDokD0c0j3YYJwUmddsBuF/hfzovxsxmwuPF7gRgsJwI1TUBv0gf'
    'fsMYoyH9YZLNfScCgP0T8vSshu+nNHmsqTN49hbJfq88vaBRADYC8LjKUEcHZHXFBgCRPvaSeTQ4'
    'A03VNwAOINmhSIowRr8DxXdYU/P5m0L3yzz/OS/CzbdWLsPI9W4BJ8ILObqxd8jRjd0o4lS7tQH3'
    'edREvXLgBLMonJInJ0K9gEcneArgUwmHjEWuhSN5isL3jJBJO21uQIa8lnotXODspH+lyJ4TkbfN'
    'YpwIZ4fqYxddX0NyRZ7qLcmNvY5JWtYR6B54nG3T4TGRfg7gqIwa+jg8vrP58EjonwZwQNxpA2b2'
    'KTxS+UcBzIJ39s6XSv/liPhzAOyl3n65ZE7WSBbXc64GcDC8M3U+VZnmwuPu7os/CNrL2kMvgEeH'
    'PBLAr/BOWzhJ9QdEn3hREXEbgLcAXCMm2TjcD28N4cIiGUFXwjso4EFZV6vgnSV0I7yP5Q7FCH3j'
    'WlXak/gKlKcJJD9zb8eh2JTlMZL/Q7KxPqSeoCUjbxVJ/kpE97ya5MvujTkUmwJNirCvV5H8eznn'
    'q3dEvo5wb8yh2BRoezkdftKypnEk9y2CfAUVaA7Ja93bcnBwcHBwcHBwcHBwcHBwcHBwcHBw2ICg'
    'PWIf+lwUGeIfK7f59inx6mo94wJtfmzvarvwL7NzaXZiOpS6vhtoO38ufAq5KFAQ08q7vO6ALYd8'
    'owO8vTSDANQ3s6b5erCZLQRQCd7O4LcBbBWxp8opkEOFRl39vqxV53mFma3VieivKaheUShQgKSh'
    'O8krxbU1XxvJGiQMq421JGWR9t+cH1gO0jVBbpL+KpO8RUtaZopLrCQifj2Sd5H8VmQhU0neFpc3'
    '8boRwHsKGhga/htGyOS0d4RkFdXTmIhnGckfSI4Phf9IcliKqfItyVdDYYNkGrUPhR+jvF0cCi/R'
    'cz6JSeNd8aBHUXUloXXGNrW6wG13VVENAgEFGhJRae/FNOqqorD606ajHBTotgj5qM1uI2NeaL8k'
    'BUpAmRVI9x7UiuVNQuF7SOacUPgzJGcn1EujMPOLwmuQ/FIdR02FNRcp5Yiore4iiPwT84wIKkny'
    'tpg8xOFnknVT2pFPCbVfDm0v0xwoJHOhZNoXxQgUwIEA/gfeHvUdAHwMoDOAnhFxewNoC+B9ANsB'
    'qANv41mPjOnXA3CM0msIoAWAawGsCVVWdXhbsT8HsD28rdqtAVwAYE7MUL+N+Bl8Dq9TQ/wGc/NU'
    'h0/JLg+vWD5G5XguFD4OwCYkm8c8b9dAvGB5luuZzQD0F/Prk/DIMvrEsBUN0kgQZmT1ufceiqm7'
    'daA5x1cAemoeEtWgK5FsGUjr6wK33W/0ew7JTXPgyij4CHRnKHxXhd8XIfO07u0YCn804whEkj0z'
    '5K2E5JI0XrayeuFKOQKVaHv2m6GwWSRHR8T3+e+O0vXZut5D19dqRKsVk8czFX+MtoF3SSnTCzKt'
    'KwfCpmc9ikR8AB8mHasS8o4tI3ldju+oNCNQVZKDtQUk0tsnYsyrNHIHzf4O4tTYmeRzJOvkcwQK'
    '82d9Ao8CKIqvrRk8/qxPU54Rh2Vm9lKWiSOAMwB0lznZT6bCFuVt+ipvzwL4G8nNFfx3AI01OoUx'
    'WaOGz/CyPzxCFp8YpSOAyWa2NCa9+wCMgEdA0i8Dkf2DADbxn69OoBWAgVk6LpVhiJllpbRdC2+L'
    'fqGxGn9wwsWhnSyabWS1tAFwMTz+veWyro5CGSjBcpmAxSVSFq62H3JoqINlStymBngagK9JnpjP'
    'gTimrGmkhU+rLo8KmG8rAbwQUY41Mnl3FYFKFwA3yHT2FejdhEa9qVzFANA1A9n5aHj7+U8MmG/z'
    'AWTha7sdwDwzuzmDe7kKgJ3hcQjcGiYFKQD2gUef9haAljEd/CoAN2t6UUP1dgM8yq1f1Zn1zYvC'
    'B0y4u0LhHeMYXEg+q3s7hMIfyepEKGOeX46ic43JfxaS878p7gWh8CfiTLhAnKmi7K2sjWhDEuJe'
    'p6/0+8icqiWq305K5+gEU3aMvsQfK1Pvngzl+pc8eJtL9u4MMmeIcbZKju/k4jha5zybcOektbHy'
    'mgMtU4Fqi3/tw6DNHpLxydjH63jIjbW3f2U+FUjeptEkDxNPdjV5uWbIBq6UINsiMGfYLCWdzRT3'
    'K5V9Y/F8L8ugQNdomcmpadugSR6gOMN9BdDSlOEKb5KgCL8rWICk/tCUcjVWPY0NUkGlzAU/izvS'
    'JUX2OKVxcIEVyKfM2q7YFGhozNEelWImaVPK4sbOmLctE1yrg1NkTQqR6sZW/LcjeAruy6BAWwdO'
    'AViUxKwjxfRPYjhAYRfp+rsYmT004gwKeb7e1fe65in14PPhTU2J11RlKNV3oIAydC+wAl1WyLNu'
    'yzIHegjA9QAWyDYcDKBb1HGFZrYCHn/WfzWhm6NJ2ot5nqh/p8n2iwB+0hzocwCXw+N6S5Kl5iZv'
    'aeKYhhPg8cCtlOv2aE020/I4VfFqA3hRdRMXdzGAz5Qf3wkwIsp9rcZSX/OsbwGcG5pP9dJ7fCbF'
    '3BoWmK8loanKUJbJPQBUL3DbrR6Y5xTVCNQ9D8/qXVT2qQMClsVWBU6ni9J5OmkFS2lHIM0DmwXO'
    'k6pTnvXq1sJt+IpTSfPXQwCMN7OvCpzkR7IQjgUwt7THQ8aUpS68j9Pfy1s5ycwWOQVyKJTynCiT'
    '6jl4rvnbC52mmS2R2fuBFCnfJ3ATHgXwGADHl3cdV3bN7C+BOQDuMLMX1kdiZjYiMKfL53MXuk7f'
    'wcHBwcEBAP4f8DcSvxYP+lAAAAAASUVORK5CYII='
)

def get_png_data():
    """Return the raw PNG data bytes."""
    return base64.b64decode(_png_base64)

def get_image():
    """Return a PIL Image object (requires Pillow)."""
    import io
    from PIL import Image
    return Image.open(io.BytesIO(get_png_data()))
