# -*- coding: utf-8 -*-
"""Font atlas resource: DejaVu Sans Mono size 14

Font: DejaVu Sans Mono
License: DejaVu Fonts License (permissive, allows embedding)
Homepage: https://dejavu-fonts.github.io/

DejaVu fonts are based on Bitstream Vera fonts. Bitstream Vera fonts
are released to the public domain. DejaVu changes are in public domain.
Glyphs imported from other sources are under compatible permissive licenses.

The full license text is available at:
https://dejavu-fonts.github.io/License.html

This license explicitly permits:
- Embedding in documents and software
- Redistribution with or without modification
- Commercial and non-commercial use

"""
# Generated by scripts/generate_font_atlas.py

import base64

font_name = 'DejaVu Sans Mono'
font_size = 14
char_width = 11
char_height = 19
atlas_width = 176
atlas_height = 114
first_char = 32
last_char = 126
chars_per_row = 16
baseline = 14
ascent = 13
descent = 4

# PNG image data (base64 encoded)
_png_base64 = (
    'iVBORw0KGgoAAAANSUhEUgAAALAAAAByCAYAAADzl1vhAAAb0ElEQVR42u1de7xWUxp+Vqd0lUrh'
    'dI8U5Z5rGTIKoWQQuihqQsKkJqGM64yU+0jIqBy531Mh4zJJRRmEooiO7miaLkeqZ/5Yz8eebd++'
    '8+1zSev5/c7vfN/+3r322mu/613vXut91gs4ODg4ODg4OOyYIPn8dlbfc0i+GyPTi+Rb7umW7IMY'
    'RnJNEgUjeR3JurRoGiM/iuRt+vwvkmcWV4FJ7kXyXZL/JfkMyeoJ6vs3kitV16IE8v1Ivp+wzXYi'
    '+Q3JjjFyFUh+RvKMhOXuR3Lcb1zfWpLcQrJl5liFclrXowHMIFkZwGEAZgTcTEWSI0kuBdBZih6k'
    'FH8D8BiA3QGsBjAwppE6AhgAoKOxqJLyvXUDsBXA9CghY8w2AA8BGBRT3ztJXpx5liRbkZxKMv83'
    'qMODAEw1xiwstwpMsgqAQwC8A+BwAN8YY1aE3MwfAPwewMsABgPoH6QLALYBoP4qeK61e4B8NQA/'
    'AphfQrd4LoDJxhgmkJ0MoB3JxhEyQ3SPDwA4EcBQAAOMMcsj2rgnyVnbmfWtC+A8ALd5j+eqwBml'
    'SKOCh5IkgE0AdgKwEsDbAPbWUH6R75Q26o1fANhmjJljjDkroOhhAHrI+u4B4B6SDUk+oIftxysA'
    'tgC4vARHl7lJBI0xCwCsA/C7BM8h9WdSzjAAwAJjzJtp9orLSH6Vck/7K8m79fltkt1C5AaS/Jpk'
    'u6QvcSRrkbyF5KNeP8onM5zkMpJFJI9K+d52VmfslMU5n5McFuNCDCB5AMlxJFvHuRDbmwUmWZnk'
    'CpI90i64F8m5KZf5AcmTSO5CchPJWhEvOYP1ovMjyX+SPC2iAQaTfCFKKUkeQ/IHko1IXk9yqYYu'
    'kFxOct8c762mFPiktBQ46UucXjTDML+cK3BfPYtK5bmSWyIaeFzMua+Q7EFyg9+6kTyQ5LSMcpO8'
    'QL15GcnePtnbSBbosyH5ssqurE5SJYX7/A/JPglljeR7ptzWqVtgjQQ/I+Wy55Mcuj0MFWeTfFOf'
    '7yF5U8Lzntf/qSRv9/1WlWSePteR4u5FsplckN08sn8h+S+fy7FI03CvpXSPL5O8J4tpI5JsUt4V'
    'uAR14iRNgQaOxBVyLDzRPHAW+B2AfwV8Drr2XSR7k6wPwJA8FMARAGb6XoQ2GWO2emYkoFmJbbp/'
    'bxs8CuBgkjeSrAegIoDXABwJYFJK9/gYgFNImgSypwF41xjzdRkqUMay7pNyuY+r3FoxooMBPGSM'
    'WVsSN5eqApP8kOQJ8n83k9w5QrYZyQe1KLBVvvCABNfor0WKlST7B/x+BMk3SK6T33UfyRFyO+ql'
    'cI+ZhYwTYuQqkFwYt4hTCgo8Ts9it9JWYL2YbiHZDL9lbIdLyWcnXEp+uxzU9QuSY8ro2uNJPoXf'
    'OrY3Bd6O2rWxZoLql8G18/XifJR7Eg4ODg4ODg4ODg4ODg4ODg4ODumB5FWKFdioNfsGIXKVSHYn'
    'OUerKT0jyjyM5GSS3yuia3xIIDlINtfvq/T3NMk9E9R7VEjMcOb3vwcECP09orwTdG+bSH5Csm2A'
    'TI2I4KOzA+RrkfyHVvTWq/wTQq7fgOSTJFdL9gWSDXdAfaxM8mqSCxSoNTt0XlhxBZv08OqTfD1s'
    'tYjkySQnadk1ToGfIdmV5K4km4j6MzNE9j6SZ0k2n+SzJBfG3ORxJGdq0jtKgZ9O2GhttXQ6RPG7'
    'zUmOTHhuJiKuZsBv4/Ug9iZZneRNau89AmTfVCx0I7VFAck5O6ACn6J22pNkbcVxryJZIUh4Fsmx'
    'nu8HSjkPibkIswn3I3mazslPINtJsmEWu5biZfdVAHoaCjyluMuXUrzxIb994I2UU2cmyWMDLPs2'
    'kl08xxpK9qAyVKZ6JIfmsuqpDv4IyXbFPP8cxUb8TMzNEAHzABwM4D2P/EcAimBJlWmiISxlpyim'
    'so0AXATgA1g6UBDug41U+izBdU+Ua1RI8v6gIBL17GMAPF+Mxm0B4FhYImYQHgPQSaGc1QBcAGCR'
    'r8292Ob5nIlcOzji+kmju7KVPZbkJABLAZwO4Enf79kEyr8LyzecRvJjsWp2Sdi+DQBcD2CcMWaD'
    '/8c6uuBpvuOFJEekZYE1dH5O8qEImVM9DfDvoCFWcr3kR2ZifaMs8BCSJ8q6HaHItWkBcrV13csU'
    'GbeR5EckT0/ohy+M+N2QfMBzb0tI7hci+5YYJg08LsSPUUHdaSqwogH/pHZaQXJ0rmyUAD04n+QM'
    '+fgPkWwTpbxqr7GZ5+0X2DWjwBom5isQPDUFVnjgU1LKGjGyhmRTks+RnOenkmhIXUWytedYqAKH'
    'vKRRVjOoHb4UybQ6yctJ/kSyVUR5lVSfKAW7V/feUtSiG3ROkA/cSP7/9yTXiKf3KckhpeQuZKzq'
    'BI0WJXmt00Tjmh8hc2PkOwDJPPXwvj4l2kTywpQU+D6F5uVncXN1g0iQPivtx4wE5TaSbEff8YpS'
    '1ut8x1eSvDyivG46b4+It+kt3nZS+/5AclCC+ubJUnUvJQXeheQgWeCVolq1jlH2xFw7jYR9Sb6j'
    'l95/iJAQVp+HY99hNEVxn+f7AapEm1wVWEzjJTH7G4S9OJDkyQlks7HAHVRu84Df5gUo8CqSl0WU'
    '91rM7kDV9WIWpMB/TjhibC2LqTSS7Uk+JgM3Oxd+nvz/h9UZ55O8NKkPnKTw3vL5OmgKa3pc0HUS'
    'Bdbc8rck90rQ618QTb6GGBfPyI3ZpbgKLOv1AsnDpUiH6AXipZByLlZ9vS7Ej2GUGtVzG8lTY+o3'
    'XS5EC03PjVC5+wXIniGrXkP1/lL7WKT1YpY1TUjG5MocZyF6yp8/Osvzng56ZwlTtuVyHaaE9XiS'
    '+4QMGcMDZNeHyB4dMu/3Bsm1GrqeS9rIMS9xZ5B8T3X5Sg+wZoT/fa2UeKOmv06JuO7Nks2Lqd/u'
    '8imXqx6zw+j16swFIjMu1QhWKUUFLhGaUAmOAskU2GGHWSAoM5qQg0OuyltmNCEHBwcHBwcHBwcH'
    'BwcHBwcHBweHsodWwjIhbkuVradShPzsuHgJbU+awXrFGpwZId+K5IvaF3cFyTtIVvXJ1PKUmQl5'
    'HBq2GuZZpfIjaOn5omz2KBY7ZZbqsTioHp76nuk7XuiPu9Dx8SF1qBFShyE+uVsCZH5VB0XFzRb7'
    'xt/Gt5BclEBnMu31sOfYkUHBPB4aViHJij4dCVrFraB6rNTc9T/9K7PehCd9AYwBcCtsRp/2ANoC'
    'GB5S8XwAhwKYDaBrzH3ebIwxAOoBGAvgCZIHBJTZFDa5yyoABwLYB8C3AI4LKfcsAHVhE770B/Bw'
    'RB1eN7/G2BDZrQGy/QLq2wXAc7BbrzYGcAKAqgD2y8WQGGP6qL1GAFjpqcP6EPnRGQEACxMaq+oA'
    'psASCzobYzblUOXlsISBDFOiN4DPI+TzYbeOjcNVAP4IG0jfBMAKAFOVveoXBdaqzO0ATjTGvGiM'
    '2WCMWQzgfAD9QgrvCuBDKWTXhA9mE4AJum4QVelaAF8bY/oZY5YYY9bq4UyJKHOjMeZ1WPZGr7Cw'
    'vxIYrQxsxpyJxpi7jTFrjDGLjTHXG2M+LOcjbVUAL8EyPU4xxmzMsciNAKYB+IOUqwt8zA0fJgO4'
    'JEG5FwMYY4yZaYxZJUPVFEAnvwXuBZv6aYGG8Nkkf4BN4VQrZGv9rmqElwG0ios2U8NVU6V+kuX2'
    '4ySVVxy8BUtV+n0p6cHeAJqjGPSjMkZljRrVAXQKs+rFwARZ3i6wG5P/J0L2EQBtYkgC+QAayEhm'
    'jNVKAMs08v+fAh8F4DVZlScAPKUh8VvYvGkVfYXXlIvxojFmNYA5MVb4GuVN2ADgJgB9/Tw2+UT5'
    'AAqLOez+BOAHAGFr/McH+JRhQdR5AbJ+tyAT2/xtFtV8ypdHokEZKPAo2Hxyc4wx61Is921Zxyul'
    'zFFYD2AibOqsMGQ2E//Bd/wHALv5FTgfwDewhMvGAG4zxvwXwC0IJl+eAmANgHn6/lKMAmd84BoA'
    '+gAYS7K9XwczupzL6OgpJ4kP/H4WPvD8kPoWqQO29+jm6DCf3VtglsqfbTuEYRVs3rxLSHZI64JK'
    '3FigTvlqglPulcsXtgt/lD7Qr8DbAGzOQoG6ytJtkyW5GUDbuPhS+dZPA3jd3/tkQZcDaFRMv64i'
    'gDolqBR+ZPJWNFD935RSvlPGLkIlWOZvGG4yxkySlXw4SfxwFkp8nTEm35OTJEp2ASwju1eISIaJ'
    'Xsd3vLbnt58VuBDAnvq/FMBg9YxhAKr4FGUn+aqdfdZkKYDOCe91s79c4RUAJxez/Y6Vq/PPUlKU'
    'LwB8pbYoq5exQ73TSpq+y0/YiQfJyt1bhp3t3jA3whizTAbtAM/97S7DOdevwG8A6KJh4GxNTy2V'
    'dfmv35eUKzAj4CWqa9zbr1gInTSF48eNAJqJft5YLIY/RXHiVOZxsHtEFBhjPimNlldbDQVwqRLH'
    '1NbeBXVLUQFqAHhVuxPVAHCFLPCrCeq/FsCFALqHZUMtBbwIoKZ85yDcB2CAdkuqB+AOjXxT/Eqw'
    'ixYNjk/Q68eS/CDgeB9NNtfwHfcuZGzQXmNXRJS/n/ZlW5dwIWOTOG5XeifHffJhCxlBE/4XkdyS'
    'hRXsSvJ9UZoKtfNM05D6prqQITr/UFHuN2gvi84h9QyrwwSS3/nZ4lpACMKsgPZaFHC9IRELGSd5'
    'jl0dQUfLI3mrSLVF2vmoVdiD6CDBQST3SJjHzMGh/EB7jBWIeLhZS7SVXcs4ODg4ODg4ODg4ODg4'
    'ODg4ODg47GDQzpBMupdawjILPGV2KK178TIyvKtVRdob9oqQysZSPSRX0beKk9mwr0VIudW1G/jX'
    'ohS9EpRPQZu9RaGhT54k+/mOFZEc6Ds2VFue+ilBfyNZ6Du2hmT/gLoZ7Tp5jufYnqIc9fbJvqzN'
    'DI3n2J+1MlbHJzuW5ELFoniPzwppgwUxz/5ShbGsDbiHrDPFG2N6KiYmibJXVLKfzcXNlxFU6OMk'
    'p+tzVZLnalPmCwNkr1EjtyW5mzIWfeVf9PAocE99b6JtRhcFLZCQnEjyXS2o1CB5TFzCFZLDSK6J'
    'kUmqwK0ke6Tv+PveBDg69g7JmwOuVV9lHOw7fqWWxmvq++lS6uY+uUoyHnf56rUlbDdL3/lNtKvl'
    'yBgLPDCmnPHFSXaTxAIrPGCBjOCysCQ+xVZgz7FXSL4cIFtI8kbP991V8a5RCqxjRwcRQWXVNyTJ'
    'R1FSCqzji71pFZR2YKt/i1XtKl4QcH6G0Fg9oC0+1MOrplHmzyH17Sjr1FLfpybdl1fP7NMQFk02'
    'CnyAOk2zNBVY+x4vz5SrwK03w+JYErsQEb8b//CCBFSPCGSy71TxDUHbYONY25dxHMZkWHJmBsfD'
    'Bq37wzQXwhINMwExWxRs0xhAoT+TjjFmC2z01wAA42EDy28PGY5fUz1GKw1Ce9jwxzjlOV/17WOM'
    'KcqlEYwxH8FGKV6eou+9L4C7YUNxv9Lhi2EZGrekpsAkq5DsAcsvm+z7OYrqUS/mBvJhmaYLYGlI'
    'fgzSQ16iIaxb3MbOJaTAR3qYAh0BTA9g7f6swLCUrG8AHCEFXhiiFLNgyY5nARgYE/g9SMr4CIBb'
    'PQ88qm1vBzDKGJNWUsTbAPRN60XPGPOZMWYPLxPGGLPVGHOqMWZIGgp8vBgWa2EZwlfDxmT+Xz0y'
    'bRZhXf14ROUug+XYHS0Ghv8GJ8AG1o+U3EMAZvrDKUsYbwHYhF+o/B0DOnFGgesrscsusJT+tlLq'
    'z0OUrBaADrCExy4xD/trAA+oHZJYpzGwgezXpdUQxphpsPG3/cvrjIpfgTO8sSrGmJbGmJEK3PYi'
    'iurxXch1eulabQC0kpUNa7RlxpgxxphusPsrtIINss8FYZYuqBNthg0I70hyb1nUIAVepE58Jmxw'
    '/9sA2kVZYFm0pbCcwsEJcq+tAbAxbs8GBaR3luvwY8o6cgds0H6l7UGBk/TKZbKkQVSPORHn0Rgz'
    'D8CfAIwg2STBtb4GsBJArkPYWlg6eaa+ebDMhe9D5F+SH9wRwFxjzPKAuv0ESyk6R8o7GzaTZtMg'
    'BRZZ4DwAFxpj3oFlft+Xgl+5K4B7AIyMIKnmggK1VTeUZwTNQkTIjtA8aFtlr5mkTDpVEsxCGCVO'
    'GR8yv9tJ+eEyuco2k9w/x1mIxzQDsLeYCX/R/HV+iHw9zTzMJXltRLkvKUPRwfo+Q9+b+eSqaXZj'
    'tG+6bb1/bth33nCSK2LurUCMlJ2yeNaxsxA++WtJzktrGq08KLCX6kEtOrQKmbD+VRoukp2lIK0C'
    'pqBeJLlaZc6MyhCUhQLvokyZy6Q0M+JSPenakcnOteiyNpM9XQseRf5s6koUuCRgau1qtWGdHBR4'
    'bchCxpYUFbiu5qzbl1sFzkHxW2vifDgctpdnlvVSslYCX4oZCbjdKbAqf4aG6QpOPX6zSt9Sc937'
    'uNZwcEjmikRhoGslBwcHBwcHBweHHd1pNiSnkbzXtYbD9qrE9RTr2y7FMp8n+fdSqHtzvZ02Tam8'
    '2iSnKEY557lNrTKOzfKck0gWZSFf6F808v3eL25hxCO7wvPG36e86uz/zdtqt/VesBtQ77SD9+eL'
    'YPcqbqAAp+k70s0r7LEkN+FOBRUDKv4GgP3deIS9AHwUxBkrRSWahuB9lMPkG+5oD6lYK2daG79b'
    'ueQ2ihJyUMQpOyvwpUjExI4RZbcg+YInT9xtQaOBOHOTNMQvRcxG09pn+EvVd25YHTKEUQB9YffO'
    'DV0eVZDOoyrzG0++tjA3pooC9dcrNiJsK1RvuoKimPuq5Zvg75nFc+ysdj4xB9eovQK7piuu4zIt'
    'VRf6eYGe9h2fsB0qkhwlMnARybeiAruyqfRgkpeQrKNAmdukzJVCfOBtJHtL9lrFTtQOkK0uRXiE'
    'ZCP55Bf7SZaSvUt7De+pv4/DlEd72C4mebiU7uwgQqXvnPFBnDefzGh1yJYiU/47og5PKwLuTHW+'
    'W9VBK5aFD0zy1CTKqzL7xCjwNhmeu3SPjUmOI/lgLu0gg7CM5GEymhNEHk43NlmFk+SBIQo8y/M9'
    'Tz1qQIDsQN1M5QQzJutJnuc51j1CeZZ7ae469gbJq4qrwKrDOpIXeI6dG6PA0z3f95Jsk9JWYGVk'
    'TWR5Eyrwan3uQfIzfb6E5Ku5tIOMzlU+PdtC8tRcXYi9SD4jRdyGX1gaNUJO+czjp22FzS8RlFdu'
    'fwAfJGAV7AGb58wbOP5p2MyK5At081tV5/YI39o+CXYHsDOAT4LuMwReXlsmj1qtUnYba+OXJIQL'
    'UyrzR89/7+eqxW0HWeQm3udqjFkDm62zeU4KDOBZWDrOoQDy1ChAeIqrIGzLxej7/idBO2NMRWNM'
    'njGmgmYWLszlHasY52xNqRzkWO9TAcwCMLGEIwhNCbSDQUCarWysb3VYOtEdxpil4swdHHPavl4X'
    'Qj1ocYDcxwAOidrTQFgJS8Vu6TnWKuTNfLXk26b8cFbAJsBpHXSf5Rjfa6bpAo14Q2PkN8JDxyrF'
    'GZgtsITSVh7d2VUj3+JiK7D2OygEcK5euvZHPGv2cL3E1YRN3VUNwOMBcg/DpuB6SC9xdUn+0f8S'
    'p07zEIChJJuR3BOWrh+GGwAMJ9lFLw6tSd5JslMODUwA4wBcSXIfko0BDN6O5nm/BXApgBuCZgs8'
    'mAegcykzwzO4H8BAkm2kvKOle6/k6kKcDZuX7Tsp4s0x8o/AsnczCyVnBM2vqnMc7/Et58PS7OcG'
    'lDlcv38C4E3YpONhD2sMLN18lOr8pHr36zk28Ag94Hmw+YEzL30/5fhSPEtTeVMBVPZMkQ1LWYkL'
    'YFNdFUSMesPkn65LczPAhLhD+jUNlkjcHMBpQVsyOKQzG9NeJNQKZXT9NdluzeWwYyvs8SSv0m6O'
    '9Um+SnJSGdXlRM2wNHNPxiGp0lQm+VfNM6/Q3HGdUq7DdM/WtZe7p+Lg4ODg4ODg4ODg4ODg4FB+'
    'oDjb8SS/J7kqRrYPyfdjZK5RvO68qL3kHH7dcJlg7kNda2TVbsdrzrhN3KJLEgX2PItpJJ8szXtx'
    'e5ntmGgAG9QzV7lJcoZCA2ao7NJXYJKTlXlnioaDT0keG9LbKpEco4DuFQq4YRBzQvK3KC3Vg9o6'
    'lf68a5IzJG9WEPU61al5gFxDxQpk8nS8F7Xbop8R7AnAP8gnt7eOt/Adf43kPb5jS0l2D7nfVSS7'
    'eL5XEWNkpOdYS9GhOvnObSDreJTv+MSgTEUeGlNkrryA5761BPRpC2x4bZlZ4N4AJsGGrD0D4Fll'
    '3vFjEGxMaTvYUMokPKy2sCTSgxWLG9TA3WDZwKcAyIfdefy8gN5eKMZsJg75MPML1uZgRb4A8AFs'
    'EpaMguwKG/z+hE/8XQCHBShUU9hkN7M85RYB6A4bWXWsgrULAIwzxkz11eFbANNhg54yZVYDcDqA'
    'CQF1Hu25dwPgQdjA+tURt1oFNuovbWxGFiTUtP2iySRn+Kzs90E7iCtR4VDP9/YJLPCqOKq+kgF+'
    'krYPnNQCe+rwb8/3fhoR/OnGBmXaS9k1v9LnbiQXhdTjUuWHu5PkR2ERYKJHfZdpL1GVvkvQfj1k'
    '1VtHyNRVzMbkhG2cyAeWbAdl+Gzrz3ZaWhbYS/35CcCX8NA3VMk8/DoPxIIE11qgBCpReBZAPZLv'
    'kbyB5AllENn1BIADleAFsGGgTwYku5kJG3xfURa6kqzvYbLOQRb+HrXVQADdI3K5PafR6mR97wng'
    'saj2U8KY+wFcbIz5JERmuCzzgQCGpN1w2jvjSQDvwJII/NffXVS0/yhT5xXqUPuQvLOkXuL8MgY+'
    'WkcWw0uSIbw5bJqtWrCJUArSGGB83/Mi6rAENlnNWWJO/z7AfYBcDQPLTmkBG498XJQCq7x95Sse'
    'EVGHTVKEXiTrwiacmRChvNUBPA3gcWPMxIhyb5Jr9jlsbHTao3hHAOeqzfYIEGmn+2oEoAcsm2Wx'
    'Ouz0XC8e5kJcECD7pTdNakIXYnox6nSmiJh5Ib9Xi7quR26cN8zRkw72oBD5K5SI5nySSyLKnUHy'
    'fu1Of6T2iFgXxnCQKzNNlPb1YUnPJdtOL9MjMkzfCNmJSmJTNWG7DiT5TQm4EFeQ/LgsfeCtJHtq'
    '/4brlUCkZoDsNfLl9lMs7BtpKLCyxV+i2NramhWZH3POMpI3RfmH2ltijZJm76ZEMlEK3FB7HcyP'
    'SZo9Snsc9PNsF7A+ZI+D/qpDvr6P1QYrUfX+QgHywyJkzlenaZHFs+6TxR5p2SjwMO8WCmXhA0+U'
    'v7VKMwJ/MMasCzhvFCwv6V0NpQUp1edhDbHvwVKv68sHjcIlsLnaNkZQXsbD0ofmyD97KsaVKZSP'
    '2xq/UNCDMFNv3a9ru4DZAN4XIdHvn94B4I+enHODYalTUXSsCXJ3Ho2QaadyFmYxjVZS0115yJFO'
    'lasFvrOY59ZIMpQ7ZN2uo4rjeiUo95gSWImrqTWER8vSAjuUH+VtAaAfbL7ktJEhoE4Pmi0oRl0z'
    'sxv1AdzqLLBT3unyrcf455/LoC6JfWAHBwcHhx0J/wOx6trNimXjsAAAAABJRU5ErkJggg=='
)

def get_png_data():
    """Return the raw PNG data bytes."""
    return base64.b64decode(_png_base64)

def get_image():
    """Return a PIL Image object (requires Pillow)."""
    import io
    from PIL import Image
    return Image.open(io.BytesIO(get_png_data()))
