# -*- coding: utf-8 -*-
"""Font atlas resource: DejaVu Sans Mono size 16

Font: DejaVu Sans Mono
License: DejaVu Fonts License (permissive, allows embedding)
Homepage: https://dejavu-fonts.github.io/

DejaVu fonts are based on Bitstream Vera fonts. Bitstream Vera fonts
are released to the public domain. DejaVu changes are in public domain.
Glyphs imported from other sources are under compatible permissive licenses.

The full license text is available at:
https://dejavu-fonts.github.io/License.html

This license explicitly permits:
- Embedding in documents and software
- Redistribution with or without modification
- Commercial and non-commercial use

"""
# Generated by scripts/generate_font_atlas.py

import base64

font_name = 'DejaVu Sans Mono'
font_size = 16
char_width = 12
char_height = 21
atlas_width = 192
atlas_height = 126
first_char = 32
last_char = 126
chars_per_row = 16
baseline = 16
ascent = 15
descent = 4

# PNG image data (base64 encoded)
_png_base64 = (
    'iVBORw0KGgoAAAANSUhEUgAAAMAAAAB+CAYAAAByHB4CAAAh5klEQVR42u1debyXU/5/fypFRUWT'
    'bClKlsZSSQypyBqiMJaxG0lM9nUYwxDZh7Fm9ytMSZgMoixJEhkUrUMq7dFGdd+/P877GY+nZ/ve'
    '+/12bzrv1+u+7r3n+ZzznHOe8znnc875LICHh4eHh4eHh4eHh0eBILmC5OM56E4myejfJajPaSR7'
    'pjyvRfJhkotIfkZy/5zltiP5LsmldPgsZ77pJK8psA2Pknw2g2YzkotJdiqw7MdJHrgejtND9d3a'
    'BGnV1oFK1yO5imRb/T+N5Gk5sqa17WIATQBsB+BSAM+TrJtRj+oAXgLwBYDG5tCqRG1uDeAUANel'
    '0ZnZfAB3AbiLZDV4ZOFKAK+b2UfrDAMA6ARgMYBxJJsDaArgjYSB05HkSAD3AbiV5FCS+8aQtgPw'
    'pJktMLNhABYAaJlRjy0ANAIwyMx+KHGbLwfwtplNzEH7EIBWAA7LYKreJB8iuVUo7QCSI0husx7M'
    '/r8DsB+Am9cpEYjkfSSf09/nkvwigW4Xkj+SvER0F5M8mOQrMbTXkHyFZAOSh5CcS3Lj0PO9YvJU'
    'IzmL5N3l6J/cIhDJhiR/InlWAeWPIDk0B93+JF8g+Q3JcSRvI7nleiL+vExydKXuAQooryGz8Ugk'
    'zyUkf8i5B9hQMvZikhNIdg7JiO+QfJpkrZh8D5BcSbJ9CT/UcWrfDgXkuZHkEpI1Mug6kBwcYoB+'
    'JLfIUf5Eklesw4N/V/XpUaV6wQ8kHypBuVur4tuTNA3YwxNoTyVZpsamMkBM3iNIvkeyP8ntU0SI'
    'lSSnkpxEsk6J+vJWkssLzHOs+um3GSLQwyS3CjbB+skUgX4FDDCA5OckrVQvmEGyXwnKPZbkXP29'
    'sz5ywwTamiTfIrlcH+y5BPk/oDeSR5N8n+Q/SDZJoW0mseRcki2iDE/ya5InF6nNT5D8tsA8ndQ3'
    'XUpxCrQuM4Amz1Uk/1DoSUkhWKSfYmMvAKNDf082s3kJJyI/AegMoBuACQDaAxhO8m2Sm0QHNID3'
    'AewPoLuZ9QJwLsl5JKeQPDpSfDcASwA8ZGaTAFwA4GySR+h5fQDzitRmA8By5EE58iUNmm5hWVMH'
    'BDeHkpYU6T3tI2Lt5BKMocsAzAAwYF3i2lUZ8v/LGflPI9kzNFvfFLMHaBT6/0SSH5HcQmf9c8Mr'
    'Asm/kfw6UsZAknNI7qv6NiyiCLSikOU6jwhUwTqtkyuAvucKkucl0VTJY1AzqwFga/3bAkB1APMB'
    'HK3z9645y5kEYEqorCB9hZnNCSW1AzDYzGaZ2RgA4wG0DT3/BMA2JMPn/ucAWAbgNQDPJ61M5cBY'
    'ALUA7FBAnt0ALNXK5/EzLoY7Qn+0pAxQ7FMgoQuA6WY2GUBriRlvpdThYpI3kdwDwIYAapE8HsAu'
    'AJ7PeNdHAI4m2ZhkOwB7iAkCvABgDIDBJDuTrA13ifYNgI0itBXFmwBWwp1Z50UHAG+a2aoqMOsG'
    'J3gzSlR+K5U/NoOugSapu8xseakbXXQGIPlMsNEkeSXJURn09UheTnIMyWX6GU2ye453mc7E55P8'
    'L8nfx9BsQvLvugtYrlOFa3UE+WNwU12ktg8k+WZO2m1IribZFVUAJBtpgE6vZAa4VqeG9da7dU97'
    'gF7rcP1ba1+xUw7aG0h+WlVUIbRCkuQtlViHOjrQ6LteCn6F3gNU0TY8GtyAp9BsRvL7QpXhSlzv'
    'ayURNPZbEI/1cfJ5jeQDvic8PDw8PDw8PDw8PDw8PDw8PKooSO5I8nUZfc/W7WitFPr2JB/UjRtJ'
    'Nk2h3VY3qV+p/M9IXiBb2zj6TUlepUuepSS/JHmd1BCy2lGD5CeqU7cEmtMSFO36ppRbm2Rf3Rav'
    'kPHMbgm0s1OU+c5LyNOd5IdS4Jslle7tUupzlhTVfpJK+s0ka/qR/L/+6UpyuC7F5pF8PtH2QVf9'
    'M0gOkqlga5LfkfxHAv1mUjU4RwMziwFelRXSfrqp6yorpgcS6K8TA+ykgbe/6jMkR8MvJbkgJwPU'
    'z9mZpjPuseqbmtIcvb2AD3JjYOAT8+wQGfTcoG+xnWwVpsYZ34RUls+XGkhHabHe64c+QHJz2YR3'
    'ILkxyd3Vl2OSMlyo6/ctQmkXyQqqccbL+uRggEtIbhRJu0t6LJvlbNRf9J7fpNA01Qx6UZEZoId0'
    'gLYq5wcx2Qa/m/D8Md3qWswg7xxDP4rk+zF9vLJYqtm/Qqb4q/pz0yAtrD9yMIDPzWxWKO0NADUA'
    'HFDRl5vZbTFaeTNUh7yG2XkMPu6D0/4cV+T+Ow5O4/LbcubvCGBbAE8mPF8Z0z6GnkWxI4BPI2kf'
    '6nvtX0UG3MayonuvguUcJvHlwPKaNSpfBwAL4Yyb1mCAHQBMi+SbFnpWCnQA8GPMe6OV31DmfucD'
    'eMrM5ibQHacyry6gDl9Khp5C8s8phuW7A5hC8k5pjS6VSLRzzvecAmAFgCT9nrsBrAZwjQZOMzhr'
    'puEA3i1wQmie0pe5tCnLS688raXJOxPAbXC+lCqCaXBuaV7X97qkHKvcXXAq5j1lPbhGpReSfIrk'
    'b7QXeETpZSTvqagIFJNnP5V9bwZdeDP5dNIAlRw8k+TV+r9jhgjUg+SfZDXUSG1YGfU2EaKfL09y'
    'z8tuoKkMyr8muWFGG2pLLMvy9NZZm7UAI8LLdYwINCpGBGLUAm5tMIDaeKY28ST5Ack/Rs1RI6Jd'
    'EpYkvKOlLOZm6xDiGZIdcrThPJXbM41oIckntXmYRfIxpTPLF06hDCCjiek6Edo4B31tuSyZSfL5'
    'BJr7dTqzYR4GSCjjHjHltgn9s0yGFkHabnrHKRnlniy6w1NoDpZdwaVi5u1l5P9ZnNc6nRiRZC9t'
    'mveXu5MVJG9cy6LO3joJnKsVslWJ31dDTDRU+9ZxKbQbaOLqH/c8LAItArCJmX1nZluY2emhwbmo'
    'iJWvCWAwgLoAuubxsmZmy+TB7SIAPaK+PHWq8kcAl5vZigpUbzicgXnrmGeL4YzyF4bSPgdQJnk8'
    'DacC+A7Av1No/grgYzPrZ2aLzWwKnEXTLgBOi+mTQQB6qU/mAbgfwLkSo+ahcrBSIm2pLdMI4Ce9'
    'a3UG7ZYA6gEYmcUAXwJoFnke/P9VESvfH87e9ggzK7Tc/+h31FCkgdoyIOTJIDCffKEA66S0TfaU'
    '8uTTqVFnAP+XYbLYAkDUK8Jkld0yYWK438yam1lNM9tZ/VM7ZnNcUpjZ+xpo1wI4EMAEiWhnF1kE'
    '2lH3NN9oEl0J4CAza51SvQ30+6esmTnpGHRVMY5BRXe9yjuinKvH7/WerjloyyMC3S4RqEnMs2tS'
    'RKCTU8q8QjS7Zbz7E5IfRNJaKG9et4rXSHytUcmnP23khGuJ+uzRCpa3sxiKckp2adGPeiV3hi/C'
    '9ki7CCuUAXTuXkby9Jz1GSY3gVuTrKs9wAyS40luUFEGIPlPzUSb61Kvp+Tn+xPoG4VuExuTbELy'
    'TV2upN2Wf05yfI76nqX6BnuAZrqVX5zAkC10K72NTo3OUv2PL+apTkWM3LU36VWEY9DD9b26FHoM'
    'qgsw5vK1qiXmDXHtHM2IaR93RsISdlvCDJeEQ2Lo99Cp1FTV50udANTP2fAsBmhH8iVtrH8k+YU8'
    'S1RLKXNXDcol+nmFZIsU+j1Vh4tz1vlU3ZYHqhCDk+yC5ay3T6h/RpM8stjHmqU2cl8Lq1F+BvDw'
    'SDiarVQjdw+PymQAb+TusV4zgDdy9/Dw8PDw8PDw8PDw8PDw8PBY36FraurmOO0W9eXQzW+ZdLpf'
    'UlDotPLP1O3oMgXJ7ptgIxvo0a8KbIczYoRdknIzfUUMfasU+iEJ79hYkRinyZzyPwpWVz2h/gMj'
    'aTVU/l0x9L1T6lM3oT4N87Q1pT71SH6s9mwZeRYouB2YY8z0EO28cF+EImQuickT2IUcFklfEad5'
    'oGftSb6rsTNXcZJ/4S69WiTDJhpgk/TBJsk4Pc3TQFc4VeHfwMXxSsO3ZmZwEV/awEU1GU5y64QG'
    '3ALgDgB9ATSEi9V1EIATEsp/Fi66yl5wGpFvkTwxo07NbE2kudU+N4a+W0zdN4TTSD0IwLFwGqt9'
    '4IJg713RicfM7g1eDqcS3D9UnyUJeeaF8mxT4ES3EYChcJZZXcxsZhHmz1r4pfnmMQiZKybgnJz1'
    '3R7OguwzAI3hLAU7AhgYywCKmfUBnN3qMfpgxwM4AsCdKe86DMATcNHW84Yuomxrb4CL/HJwTANa'
    'A7gUwEVm9pxsAsbDqdvOSCl7tZlNN7Nr4ULj/CNpRiwxLgWwK4BuZjZWYZmGiyGWrWOrfA04U87d'
    'AByiqD3FwKsAjtY7amksDUuh/wrA4TmDe18EZ6vRx8y+N7MJAP4M4BBFAVpjBXgYwIdmdoKZ/Ucf'
    'bByA3wPoGeePRyq+TeCM50fmZYDIDBD+HcbpcDrcAyIDfIGZvZqz/IFwxhCVET3lDAAjzWxapP4T'
    '1K/ryuA3TSQHwNlwfFLE4gcD6KZ3dIHT80+zEXkHwCQAZ+You4vGc9hA6m39PugXDEByV2W4UP8f'
    'L/O6uXBWRssQb2jdVcvv23CxrXbNCrocdKpUfK/XyhEnQ+8FYJKZVWS2nKjfu6/lQfMbAE1R3Nhh'
    'lYU7AZwE4Dgze6fIZY/WGNxTUscLOfI8DODMjP1mdbgYbl9HHs2GM6LZIboCHA3gVTObL/XexwH8'
    'CcDOGvh1AdRMYICPzWyxGAAZs+1WstYqA/BfONPDoxPkyc3FHBXBYv1OM56YFrMx3DeF/v4Y+mh8'
    'sEBxbH6B9T0+Ep93ZSUP/sM0DqqhSDGIo2NVk9+xAI7UipCFJ9S/B6fQ1NU+c2lU9NZkXj/KALvB'
    'RUqEZvx/mdlguR+5MOlEAS686Jsq/AtxWNccm+BqcKFLBwF4JSXAXEU7vSwHTdwm+N0CN8Fjs+pP'
    '8t7Q2H48aRMfLhQ/m/NVFjYG0BPOx9KDJQo4NxhAbwBL84iGZjZfef6Yk8FS0wMG2AxA4GtnJ7i4'
    'uMELpwL4PqaQw5U/HLr0TQCds/x3hjbBfTTLx5n8zVG9KoKA09e2kfh3oX4N2txbg/q/VUzESZsk'
    'XjKzBwGcrVn3jhK8f6Rm6hcKyPMQgK5h890Ilkg0jzv8qB2SDP7HAGVw3hCg31HOsQTxBwCGhZbs'
    'E+Fi9ObyJGdmZXCG33HOpT4E0CLqTrFABNZUa1UWVxDurwH8FlUXtUODJQnL1J5xcI6lziB5UJH7'
    'apWZNTSzPgXkGQHnpOCMpJNAAFN1QBOWWhprVf0qygDf4Wf3hF/ABYoOMjXTUhguaAPtpB+PLNm1'
    'ASwv8NRlKzh3dVE8qdOh30fevWmcCWWSTK3V6+VKGGCPA+hYXl+iRd6UN43ps+BQ48ucxVwLYDqA'
    'h/P4cloLeATAWQmTM+BOJveMOC0Lgo+/FmWADwH8LtjkAThUN3sNE5a9DgA2gTvHDXPecgAjJB5l'
    'fZRGJP8C5/LjwRguHg3gXgB36uZwI51Wvab9Q1K51WSwfr06qHce30MlwK0aXC/Ie0QtknuFN2Br'
    'ETVUj/NJ1pfzgqvh7lNynezoNO5czapVwTzycU3aNVNOr6oDuEsXvC0B3Ajg32Y2JjpotpFheAv9'
    'HxyDzpOnrwXhjSrJO+TVedOYAXi+JKI9IukvR32/yJA7zaWIybnqeN1MTyd5S4YqxGqpZQyNOtCK'
    '0KepQjwSQ98q073emnnqywN24LFtCsn+JJsn1L8kqhDqx5MUz2CR+v71NA9ucfVR+jNSZekYSU/z'
    '9TM7QtsjyYuIXMgnqUI8EkkbkOSEQc/3Ifmexs58uWqpl9Tg2+V7pTY8PNY3KODDILkv6VqiIy8P'
    'jyrNBEbyRIWVWSCx6OMKnsR4eHh4eHh4eHh4eHh4eHh4eHh4eFQFxNyMztfFWPeUPFGj4wfjIoKI'
    'dnqo7B8V4fzmNL0ShcUcqfhcM0kOjDOiJ/k4s3FgJM9Ekm9E0hrHBaRQ7IA4vf8grtjK8L2J+u6h'
    'lHYtC9/uKkbBIpIDYmiHK/ZZnVBa7yS7Bd00L4kxWn8kpW9WpNT1tBDdogSaOro5vrnAMdc1Uo8a'
    'OfL00G3/FJKbl4IBmoYGwwNKOz2Gfnv5sX9AuhY7KejdKykM8LL+3lDeJBaRfDuBvruu3C9XAIvG'
    '0qmflaMtK1J07svDANsq/bKYcj6LtkEqHsMS3ht4Zjgvkn6B0vcOpR2ttCMjtDVITogGntA3WEXy'
    '2pzffBeFiB2XgwHqZ5R1rYJ51CvH2OudhwEU9X25AqaPJjm2aPbeUQYIdfQskh/G0N+nBm8YSgss'
    'mtqkMUAo7YYU+vdJvh6Tft7aZgA9m0Dy1UhaEDziykj6UyQ/T3jvHspzUCS9unSeRutCspZmuSEZ'
    's+dRobQhClpSO+c3H6nZtF0RGKCBJsQrS8EAYtYFwSSkSXcUyVcrEhKqWtpDBXWbip9N/MJIMzo+'
    'OOf7A1XcODvizfGzYUm4TvdVkpQ4DMC+kfBMnfU7aqQ/KWiTNFNJcrieBTrqX0XatRrOMmovOLcv'
    'F6oPzk/4Ni/DqfzeJObZG8BRAK7MY0dN8lQ4rd5/rKEdWQ4oeuaDAPoUW3NAKuXDANxsZrfqfd9r'
    'nNWFU40uPgOIs7YTE/xitkK60XHLnO8PVps4K6mPAByWFVxuLTNAHTgz0DADzEbIgi40uDeWONAa'
    'Lpxna3k/2AbO28XXMYPoHQBPw6kbXwXgL2b2TUqdLoYL0Xqq8oxV/qwB1QBAP7hI7lcXsY/ugPPC'
    'cUYxO97MvjWzJmbWL5L+g5nta2anFZ0BtMG4V7N/NHBcbqPjhLJrSlX5fDizu48TPu50AB9LpfVW'
    '6dNXFt5W2zpHGOBVtTu6AgSzfRs4G9aNAGwvBpgia7g4XA1n7/ADnBVW2sD4FMBjAO6GM/a4MKYu'
    'cbgZzpHZ+ZpJizVQZ8IZrV9a2ZEqK8IA02TeOBHOncgJZjYwaSwXmH64yv4RznBmAIDuCZ35NVw8'
    '4U5wdqMdAIyWfG1ru6PM7Ec4++fOgWijAR3no2hSSLRrI+b5RH83Qbrvmz/ABZreEj9bMKXhGq1M'
    'wzKM+YPJpx2cje9LZja4BF11qxj4hHWVAQIvCQ3MrH3C4M8yOl6Y8L5XZDpZRx+uN37pGi866MrM'
    'bKSZXWVm7eGcZZ2cxDQFoqwcz4YB2Fsb/wPUB6/H1Pt77V8CBhgD53WvrdImJQzOZloBbodzQ3hP'
    'nB/RyLtmq74zcwz+6lrNl6nvSzFRTAHwPIArKmOiKuoeIKWRq+GMkpOMjqdm5F9mZn/TjPpghu/R'
    'MJ4AsEIDqaJYgTXtSYP/l6cwQC0489HOAD4wsyTfRZMA7ANnT/2pGKBNGgNI5FwA5zLycsn3vYr4'
    'vXtpT3KtVthSoS+co4Mjf5UMILyGZKPjt3KWcZ0202fEzFaXxzBGfQ3AYsit32BNtyuBA60ZCYw7'
    'VYO3k37SXDROgnMOME6naaPFAFvGiUC6cDwMzhfqUjObCOcF7a/FiIquyekGOB8/95RYXBwP4BUA'
    'V2JdQdw9QAZ9M5Lfhy7CWiqYddLF1hr3AEp/R882iKS/S3IMyX11cdZSgal/kKiQVrc89wDddNF2'
    'sc6wt1eQ8FlJt9nKd3coQHjbFLorRHN7KG2O0raK0NaV3fDwSHoj9fFDGW1ZFWfHHKF5THRtChwX'
    'ue4BYvL9Tvk65aDtnfcmuMqsAHL62gVAK8m7EyUTH11gUbfAeaQ+NWYz+L5mwYWStZcC2DvqcLac'
    '9R8Cd25+rI4k34VzDrZPxsnIMDhXLnPxszc9pGyEw2fsYyR/R+X16+HO/HtH6jhH/XNmoQM3Bjvp'
    '5G5sgjpE8yKvAu/BeZxYd1aBCq4gvXWr2Asev6bvWq4VQHkPTbrpryorQLE763opY1X3Q+dXxwCJ'
    'ynAVKLtgZTgPDw8PD4/UlSUPnvY95eHh4eHh4eHh4eE3D2fpprWF7w2P9ZUJbif5UQEKannLvSbO'
    '7XWJ29K1FLecJI8i+YXsaUmyWxHKvCLNOD0j74gk08kE+m5Zai8kdxRNjwLqEA7wt04gThXiUjhl'
    'sL5+Ooj90DXgrK6GAagr1fEh63u/mFlHqbpfuC7Vu0ZMQ8rgdGQ84rE1nB3ECDP7qaoMvgLphyA5'
    'tNB6hXIrw8ms8WxpbC6VL5xBJHfIyPcHkl9LY/PttCgloj9HMQuWk5xK8qaICnaY9gx5UviR5BiE'
    'Yp0l0O9M8kV5t1gqbdPtUkQUAggU8YaGVvxuKW2dora+H9IQbZ4htn2m9n6c4bEhjCE5vtnoSJ6m'
    'BX7zc+QD6eQKrqLN9f6B8vn0niIBzdQ33iNJRCywfw4k+UEoQszTJBsVSxQ4lOT9Ch1UU75zXpJa'
    'b62EPUAZyXEkdyC5lVxazIijV55+cvJ0uoLjNZH/nM4JjSXJPgpNdIwcUDEhJNEO8kv0nEJENVbI'
    'nclR1eyEj9c1o386qL2XSd36CB0wJNXnCikTvq6gdo2lEj4pLSr62toDkOylPc8JGWX3ydoDhPrw'
    'cpLbacL6SP00lORzFe0fkm3ErPfIF1Mrkp/Ll1C1kiwnisn0C+dOEQZgePBKBz/J8da2avCVOd/9'
    'mmb9cFr/lAH3nJgv7NeonpjmtCIwwCskP4qkPZzBAAx7wSB5nNK2rUwGkLbmT3k2xAUyQFv9PzHw'
    'lEfyapLjK9o/sh2fFVawI3mI6LsUQwSqptl4fDCzAQg8laWF0RwdkkWnwAWx3j2GrpPq92LOKu0e'
    'LlsYlULfBcBrYb9GZrYYzlqrdRHmg7ah/gjwfkaeMgBhh1qBF7xGqDz8EcDfATxlZv8sctnBqeDS'
    '0N/LEG9rXmj/tAMwWtZ4AYKImHtVmAHgjLf7ArgJwDY6AWidUe5PMU6bFiY0IDBX/C4PM8KZMy6M'
    'KTuOvjqceeXpUQ0pALvBGbxUZCWsBud2JFd9QlgZ+WDBTFqZ6uX7wbl1OSVN3q6o8BD5u3oR+qce'
    'nH11ePO/FM5vVf1iMMCJAJ4ws2fNbFHohCQNNWPc9jVIGOTz9btxjlONMjgLrQYxZcfRrwawGMCt'
    'Fo8KeZ0I1ScaRnbTdfCg5EK4gOPjADwTF6K2imJxtL9V9w0ALCoGA9RBxDEW8plDtg/vATRzxznG'
    'GqElL6+J5bjw0ibsk0I/HECnErruGBvz/r3XQQaYp1n3ZABbINugfqG+bWVHk/8QQPuIkU3gtGFM'
    'MRhgGICTSLbWqct5yOcG4zaSLeS++x447wwDYmbR6XAez67U8eamJLfWcVnnmHL7AWinfUk9kscg'
    '3TnTn+HsZB/USUQdknvKyL9HET5APzh3iJepf7qiOP6MKgVmNgnAJQDOSHOZr33PKgDnVrKF190S'
    'Q+8IToHg/C19rMmvwgxwKZxbkNc0iA+Dc1yVhqUA+sO5TZmqzc6hKRdKF+s9feAMyd+BMx5/L+YD'
    'vQnnXqUPgDkAroBzAZj0Qb/QarSZZos5AO4DMB7AS0UYMCPUH+fC+Q+9EsDfgr1QEU7cHgntW/YH'
    'cFRoK9O3REzwAJy7k4eini1CNJMBnAmgJ4BAVaRhJTDshwAO1zeeobHzicbbanisfeg4cUVl20yT'
    'PEUDcxP/VTxKNcjqkXyWZDuStUm21a3w/ZVcr03k/2ic/0oepR5sPUh+KDWLyST/Vmzf+QXU5bZQ'
    'eKpRJHfxX8jDw8PDw8PDw8PDw8PDw8PDw8PDA8D/YvSOUKyCPKGYJsfFWo7QHKh4BTNJ/t07VC7e'
    'x3qa5FjfE0Xt0yEyVWyWR3kwDwOIrhbJE3Q/cXhltK2a/7weOdASwCgzm5YzDGsuKPLmc3Bavy0r'
    'lQFI3igb2QtkKric5JskW6Zw8JHyj/MjyU8VbogkOybQtwrMCUneTHK2fq5KoP+dlt5FMm97PEkJ'
    'Szo2BHASgDYRO5f6MfRr+OFROCaSbB9J31QmgRfFlPMJyRciad+QvCml337xnKTJpPPTiIlmB5mF'
    'nhLJX0fiyE0xZb9E8tOY9PYpnpKbZoyTDeCCChYdUkxbCaBmpTKAsAmAUwB0BNAcTq31X3FqrSR3'
    'AjAIzmRxCzgtzKtyvjdYHtvqp37UMJ7kpnCah+PhAuntChcm6ayEjtxQVmnPAPgoYuCyqIIfaQGc'
    '1utxkTq2gLMgi4aSHQVgz4TB3xjOcGhUqHyq3zeHC4kEMe1TAAaa2ZOR+iwF8CyAk8MG3tK6PBhO'
    '4zbahtHhDoFzifM2nEnqgjySUCmlrKog592o2aBDKK2l0o6PoX9YK0X4A9yQcwV4NUd9OmYFoqvI'
    'HqCQFUDPTooaYAfe7qJWbiT/JHcfFlPOESpns5hnh2rGP0QeKqYkaWyS3EvlHBBK663VeLMc7e8r'
    'rxUH56BdQPLOAr5Brj1AiH4eyVuqyh4gbLT+JZz5WJx/ndYAxsj8b428GRiSg2aylsZ+JA8jWa+S'
    '54gX4eIHHxtKOx7A0Bg751FwdqfNSVaXT5q79GxPAF+a2fyYWXoYnJHQPwH0AHBiUsA+M/sAwGda'
    'OQKcDODFuLIjA+5wAJcBuMnM/p1CtxHJs+FMS0eUsG9HADhWp01xLk42kQueGRL9hkj8rkvytyT/'
    'r1gMsCzGOGWhluYoNkfhRt8Bvs0hdswAcAyAjeAMVBbKudQelTH6zWwJgJcDMYjkjnARMgfEkH8M'
    '591gTzgzzR/gDIYCBngv5VWPwZmb/gfOUCcN/QF0156gud7VP2PwNwHwJICRcHGaE48p1YaHANxv'
    'Zi+WsHsv0GT3GeIj3reHi0LaDkAzOCP9C+FsyQcgv+eQTAaoHeMUtwGctVQUc5DTCD0GK3MOupfN'
    'rL32Jj3gvDU8X6ROL8Oa7gFrZ+QZCBccvKlm/0UA/h1T71UavHsCOBTAAwDKtGdoiwR3LdoHPaGV'
    'tCWcVVsanpIs3x0urOw32iclDeoNdOryE4AT0iyjzOwN9cepcOaNR5SQAf6u3zvBBRKP1uU1M7vb'
    'zGaa2Xwze9LMOplZHTNrZWbPFlMEChut76Cl/JMYuk80GKrF5S3y7LvUzAYDuBdAk4xLkyVaNbIw'
    'B85LRZhpd8vI8y+4KPXH6WdQijnnKM1Yh2oFGwoXB7ghkv0V3QagiQb0RQCuJ7lPSr/Mlzh5isSf'
    'xyIiaVz5bSVazc7R78u1AZ8DoHMJGWB/AP80s4kZ9S/5JrhMruOah1wXTotzFSh5bZWMPBqQ7CRZ'
    'N88m+JAc9TlCcl8bWVTtpCPHf2Xk6yWXeB3SGEWG8KvkfnFjebWbmrQJDuV7QreXlJiQRNdVR7NT'
    '9P9+IR+VcZvjwKa3eyhtCMnpESZdQ1RRvrIMT28B3TXlGBuTST5cwk3wcpJXoDIRugfoQ/Jbfby3'
    'JOsm5elGckLoHuCiIjJATZI9xZBLdXb+QNYJh24X++t+oSwtyLOc+/5XH+AN+SDNYoDAvd7sDAbb'
    'VO+/R/9XJzmX5CsxtFuLMR6NpDcUsw1KeY/pjuT1jH7pWd57AA3oR0rIACuqDANUsIy2aQzgUZLv'
    'to2OTo8t4TsmkHyqFAygiWF13CVjZR2Deqw7g78OgFu1+X2hhK/6CsA+clhsRax/Te2lqukdngE8'
    'cg+eu7Qh3wVA94jPzGLjGh1PJh1Tlqf+B8Ldq9yhU7Jh/qt6/FqYc3J5NtseHh5rGf8PDp7B5cYN'
    'BQMAAAAASUVORK5CYII='
)

def get_png_data():
    """Return the raw PNG data bytes."""
    return base64.b64decode(_png_base64)

def get_image():
    """Return a PIL Image object (requires Pillow)."""
    import io
    from PIL import Image
    return Image.open(io.BytesIO(get_png_data()))
