# -*- coding: utf-8 -*-
"""Font atlas resource: DejaVu Sans Mono size 10

Font: DejaVu Sans Mono
License: DejaVu Fonts License (permissive, allows embedding)
Homepage: https://dejavu-fonts.github.io/

DejaVu fonts are based on Bitstream Vera fonts. Bitstream Vera fonts
are released to the public domain. DejaVu changes are in public domain.
Glyphs imported from other sources are under compatible permissive licenses.

The full license text is available at:
https://dejavu-fonts.github.io/License.html

This license explicitly permits:
- Embedding in documents and software
- Redistribution with or without modification
- Commercial and non-commercial use

"""
# Generated by scripts/generate_font_atlas.py

import base64

font_name = 'DejaVu Sans Mono'
font_size = 10
char_width = 9
char_height = 15
atlas_width = 144
atlas_height = 90
first_char = 32
last_char = 126
chars_per_row = 16
baseline = 11
ascent = 10
descent = 3

# PNG image data (base64 encoded)
_png_base64 = (
    'iVBORw0KGgoAAAANSUhEUgAAAJAAAABaCAYAAABXNd9qAAASOUlEQVR42u2de/xWc7bHP6s7QnRR'
    '/bp5TYMjd4NcRqhRHJfMhEY502CGQ8OYjNthDM4MY5IOHdfcBoPjFjFICF0MSaYav0ili0oUKV15'
    'nz/2+s1rt333fp7f8zw/pfbn9Xpev9/zfNde38tee32/+7vWdy0pR44cOXLkyLE5ABgJtE0p2wF4'
    'dnMaj3olDOBlwH9nlPcFfu90AzLobgT2B24G9kmhaZfGAxgAfA6MBhpn1DMQWEqEHgXoBhbo+w8l'
    'LTazj0LlZrZI0jzgiJTrtwHuAo4BfgzcDmz3HXp4GgJTge1LFqAKYh9Jb0naS9LkQGMv9N/vBlYF'
    'rh/gPGZI2remgwG6/pIOswijy2zzzyQ9VoBmhKRTUwRsmaTbJP1O0n9JusfMlqbcrLMKCfQGQH9J'
    'z5rZkg0mQP6kI+lgSeskHSjpqwRNY0m/ltRL0s/NrEmA1X2SJkn6vqSFrhWPC9D9U9IVQCX62jUk'
    '7AlMcrpNbequ5/dkSLmMLgKuKJPHScD5QH/gnBSasa7irwO2SaFpBvwOuBzYNlDeD7gU+C1wjf82'
    'pox2LwCaFqDZAvi41CkMGMo3cetGIEAnAzdXgtFZwHllXL8uMEC/DtA1cgF7FpgM7JQoPxoYDHwP'
    'GOXroQEJmsdq1lfAoy6095TR9qlAVQGaNsC7FRrngWXy6BEb415l8poIdNpY1OF4wIAJBejaAb8C'
    'HgoIR33/2xW4zwVpdILmWuCvwPbAPsBaoHsZ7R4O/HsBmmOAuzcGAarg/ToWuLdSzDLfwoq4vp0L'
    'xPeA+1NomgNf+tvTSuBxYKsU2ibAy8Ay4IzAlPGol00ELgaeKKPtPwTuKkLIjviWbuxgYEQF+AzP'
    '0szAOODfvosLt3ZZWwEbcB+oKqWsFfDct9iWh4Hf1nEd3YHHlGPTAzAlTTPnyJEjR44cOXLkyJEj'
    'R45N/ZXwJGAuMA84JYVmom+LT00prw/8AfgEmAP8PEBjwHnAQuDDtLqcdmvgXWBYSnncLPJ0Ck1X'
    'YJLvQlcHyvsETCt7B+iuAD4FloRsgUA9t219Xqhf30HZmOzjsgy4NkTQFFjk2/17A4uBZinMOmcI'
    '0F4+0C39xq1KGh+Btm5iaAnsAXwGNErhNxS4JkOA5hXoeGNgPnBGWh0J+ubAm4Hf2/uYdACqgI+A'
    'HRM0vdxEs53TVYcMvHVwc3cBhgBXlXDtZcD/AF2KpN/JLQSNkgXdgBdi358HjqytACXomvhAN0gp'
    'Nxe4+SE/HtcMp7hNKE2AVgJfADOA4wPlBwNv1GJALwoZioFtgQ98Z7wN8F7cqSohQM1cgOYA3VLq'
    'GV7IqJtF4w/GT4EXgWd8rBoFHr5Mq747iJ3gu+svu/G6Scbs8kBQUN214CHgAnd9eAD4aakC5MJx'
    'B9A3pbyFd2gt0D9QXlUjNFkC5OUNgJ4+vWydKDsBGAG87er3rjS/IB+g6qRgxMrPBb4CvgYGpVx/'
    'jwv0RL8pvetI6wwGZgP7VZDnvsCsjIf1HOCOtIsrpoF8IG8HTitCyHbyp7l9ouzywNMzuAC/t4Hd'
    'E78d5pqgg08tE9LcGlzY0oy7+zj/Vv55q9DNc/oD60iAGrt2fgl4GvhJUosXqYEaAL2Bp4AxwKkZ'
    'GujmNIVQs1hd5FPKXr4ILmUN1Bj4v5BWidEcBfzC6+zsC849MugLaaD67vfycWC9ta1rlQ4+tUwA'
    'eqbweTFjyunlC8lWrj0nAsek0DYCfukvI42/pTXQDWWsgW4sdg1UiFlf7/T8NAHw6SCOvoEnPond'
    'EjRbujQv9TXSZQXaFRQg97vBp5V3gaNSru/nWmgZcGdoCgN2BaYXoVU/88/tNf5ICbpqn5bfBrqW'
    'sr5JTFMjNqI3sXs2Ns+IHNk3rM5dNXJs2gKUu2rkyJEjR44cOXLkyJEjR46M18bDgXfc2voC0DKF'
    '7uW048G+i12DJcCQFLqdnc/nfigwaQjsE3MfeDVkNnBjbRK9AnQzijgF2803/5a6ZbteoD0Pxb7f'
    'n9xsdbNAEk0Cde0WK380UP6vunxn/1ngPwN0y7OOWQPDagzV/pkfMGX0cdteZ/8+PGSu8J31+b7x'
    'e3a8rJ4TtJd0u6TfSGqlKALFJQFGLSXVl/QV0Dql7W+ZmSkKenAUcECCR31FESwellQl6TlJewb4'
    'PCypraRbJD2VMlgrbH2kncnaMUYzNNGeFpIe8f7uqCjaR8faPoBmts77fbmkK72uVQG6qU53QoEH'
    'urGkxyWNNLNbStQLEyX19rreTKGZI2lgRjvaSPqjpCMlHS7p90CH9QRI0vmKIi/gA3ikpJ0D/I6T'
    '9KR/ehdofANJDSUtT/y+pyTM7FYzW25mD5jZmyk3ZbmZPehtOqiOlO/RksaY2XNm9pmZ3Wxmszbw'
    'hFAjPKPMrJyABo9KOknSif5/CGMk7Z+hzQ6SNM7MppnZdKc/JClAXST9TdJVkrq5Ngrtgp7gHXsi'
    'Q4D29fAtCyVNMLNpifK2kubVciAWSmoT+H2rxJTROeX6WTGaTmntcRVO8oi04+QaBpL61bEAHecz'
    'QYsy+ayU9JF/VmXQ/UVR7KMQmkuKxzBa6r+tJ0ANzQxJ68xsuk8FqxKqrKmkHpJmuto7IsViXzOF'
    'NZO0BZBs2AJJ7Wo5EK1diApNYTOKmMJmB9pT5RrvDEnXp/B4uIaBpAcqICQNJa1OKRvp08XJwMHl'
    'VGJm55lZoWgq9ykKHmWBsiWS4iFotpP0aVKAGrvnYANf4PaU1CSg6u+NDeKdko7NaNRXPkDJeILv'
    'eD1nevCD/mm+Ne5qe7KkzpLG19HT/jdJhwM/8kVv8zp8URng7ixb+cP4QQrpKjNbLul0SfemxUeq'
    'FMxshY9vKCjEBEmHuMfCzpIOkzQuKUDjJfVVFHrtFUlnSloRmL7i4VNekPTjjClsgWuh25OLTefV'
    'z6eOni5U35gyXPX+StIJZvZFEVPYgBIGb7H3fbCkj12ARpYgHA2831criogWegt73vuzSNJukm4t'
    '0LbXfLlwUwrJF7G+Dy1TjoZJ6hBow3xF4fhG+/rnKjP7MNn5KmCm+840yzc1cpSiXndzV9YVvnfS'
    'IB+VHDly5MiRI0eOHDly5Mix2bwVj/b9nT5l8OjtPMbWdWPjrhFf+EnFUOT3uFl/YKC85qzW105z'
    'QUp9V/pBwNnAiYHysQHXiIkJml7xiBx+Zu2YBM2NwLmx7wMDLg2L4xt+fgZscYKme01sa/9+R/IM'
    'PXA18IfY96uAPyVoOgX6dUOGAO2SUtY95AqSQts5S4B8A3Qc8PdiAlBkCdBy/39bvxmXJmja+InV'
    'Lm7u+BjoGBCgEX5suYv7+ySPLR8YOy1aBdyY0a7UmNRFClAP4JnY96eAoxM044Dvx753BF4P1Hc3'
    'cDpwEPBawGdoCz/g2MmjeUzPOpbj9GPdXaJWAuTl44uJ3VyEAF3rR8kvTBPmLGRtFiYNa/8y63vF'
    'YxSZ9T/8xoVmAKsV2cLWJIpXS/pE0iIzWy3p3DpUrq9I+ov71nwt6QeSXkzQVEvq6CdkkXS3pNAp'
    '1UGSXlVk4e5nZl8n+rwSuEiRSWSNpEvdxpSGP0v6s5ktKLFv10i6WOlW9GIUx5GS2ptZP/9+F3Cs'
    'mRVtyok/RVu5LWe+pEaSkn4omWb9GI53PlMkne45tOIDPUlRxpfhHgWkb11Jj5mt9Zt+iKKsQBNc'
    'aL8hQIos/s39/+oAryWSpklaa2bvpdT3lCIj9PZm9ljGjesVkduTZXTvaUldyslfYWajaoTHv59W'
    'G+FJClCNa0RTMzs6kMcqZNYP5bp60gXwfEnnpDT8cTM7VdJ/SDoN2L+E/q8L/LY28NtIRQbbnpKe'
    'CpRXK8o3VuM3s19IA3mOjZaSqtNC3zhe90+a8DSXdIF/ynk4cC124YZc7Ncmh9Z4rW/WP9SniOCT'
    'b2a3ulY7LDGA+wOD3JW0tSLHqWYltH22pF19vdFe0u6h6VSRu0Z3Ra4Kz6QIUB/XVGMVefBVJ9rc'
    'VJFF/ExJFymytpeaafBGSYPMbGUF7t8jkg5OW0dtVALkaR5rzPrVkq43szkFLrtakZdjHG/7VPFP'
    'Sf/wmza6hCdwhiJ3iLf9M9zMQlPPUkmfS1ptZp8EWM2UtI0L0KvetqRj2rWS7jOz9939Y5ik60pY'
    'c/xA0imSJheK7VjkGHwtaagiX/bv1B5FT8+gY/mOzYbdBwrlMf0294FyAchRSJBJKWrozoE5cuTI'
    'kSNHjhw5cuQodbV9BPBgmTyahfJRVKBtkzPO4hdzfUc3dALsVcL1TYvtl0e7HVzEOGXF2q72jda0'
    '8q4ZJ203qBD9Bui3CQrQZYXCCVdKgCrU30wBitG9vqEFaD1rvJkN2UQVbBtFByFzVBj1avlkLHe1'
    'OS+UlKSGZyxXe1rehd3dF2Zl2rTi0dc/963++il8zvIg4p+FTma65kDS2ZKeyKjreq/rOd/VDWk7'
    'c++BFcD1Ke0ZUygtgwfspsiENfsDryT9roq8Vxe7r9Ncz3j0qZtSkuMzvYh+XeL+X4uByyuhYlu6'
    'mm0VmMLWutNYc+BN4PDA9f8AfpaWCsCz7Lzj9ewHrE7eVGBP59PRz9iPBHqk8Ls1LfGJt3Uq0Npz'
    'YqwK1NXU29AV2MG9LZvW8RroND/ouV0pU5gL0GXuKXkDcHZyGi+mX+48OMsdANv5odPdg1NYgU5v'
    'qcjZqpci46MUuTd8nCCdb2YT/JpXFAWaejnGp76kDmZ2b0Z1nSW96obLxUAoXs8eiizws2O/jVLt'
    'DbM7KYoPtFDSQmB2Ct0cM3vd+zBTkdF1eR3ODr0VucysybotBXh8oMg/qZmkWZI6ldCvzpL+XmM4'
    'B8b5PZ1S2ymsmyLXi87OYI7CtrQq4AD3e+km6b3EOusrSXNdA6X54L4v6VDXQPsqihyWxBRJr0lq'
    'FwvdclMJN+p9Sd38CdwrZZClKNrIel2p4+XFaYoioNydQbNI0t4FBCz+qVdCv2ZI6lqjgSQd7GNW'
    '6zXQBF+LzFXkQjA3hW6WIp+ZWS65YwI0/SX9UtKy0LrEzMZLesmfoCuTQug0kyU9KGmcO/GTleAk'
    'DV7Xiz4o1yly71hbwrTeyddbD0oaVO6JCm/bbYoicFySQjJE0i1eV9O6kGKPSnabpLckTVYU4mdK'
    '/voQFoJdM6awStZztE/vOTYRwXndn+IPQ6kzK1hP61gE2+Pykc+RI0eOHDly5MiRI0eOjejNsI2b'
    'cxZn0JwVCnIRK//IebStq3bW28gHceFmLEPdJU1SdPiyVLRXlCPjyM1SgDZzNJU0200/JcGvne28'
    '6k6AgBbusfekuzUMTdEIV3hKpDHAhFD4EeAQYBTwErAOuD9AM8hDxRBKHeXR65G0Q8zzLmklXs/J'
    'y91DOiVofgIMj32/LRmPyC3fjWPfGwLvJWg6AG+4bW57/z8Z2qZHIiXUn4AzA32bF+vT6lAUeqCh'
    'oqQ0Sypwj5dI2t151tlU0QJY4/4nLYBJwEEJmp09GHmVx/75IkOAljivein1zQW6lDOFFSlADYH3'
    'gS09BtKMQG6yu+L5KLzd96b063ngGaBbSpve9N3mRv5AbpnR/r4ZLiafAAuBHQqMT+YayGlaAQuA'
    'zwJlBwAfANP8tHHHkNBnIe7OMcfM3nDGryqyuMfzU9SY9edLmg9My+D7Wg2vFJwrabAHYHqkRCt6'
    '0pWhfkCFrwVGKAqesFZR7q2ke8RLkg5yE4YpSr/wUoDXWGCNpAZmlmbH+l9Jv1BkwR5hZl+m3NTj'
    'I5Y2IoVPlaR7FAV6uKlM/dBHURCMUByhXST9SFFWoCG+ZjqxVAFq7x5rsxVF3ngkQfuBpAOAKkX+'
    'QLtm8F1bYG5+QpGHYAdJ7wDDPFxJEl8CO4Xi8ZjZCp9OOnh70jTacEVJ69YoHFLlZS9fqCgI1aGK'
    'QtMkb/oZinyf1gBnp+Tx+qs/dF8qJSWUJ7JpYWZ3ZozPauA1Rf5W5WI7SeMDcZEU88maqVgOsFIX'
    '0TMVZdubKWmsmY1LVFatKC3QNB/waWVMmct9jTNJ0uAU4ZGi6BsTM9wVhimK8vFH/xu6GdNdO21j'
    'ZlMD5fNdu46S9Kyk3ZJRR4BDJA1Q5Bp7rqSTgCMCvNYoysC43MzmBvpdT1HylOGxdVCa8/wySR3c'
    'Aa/Uca6vyL9pWV2/Lrcoxkc3cc2YrBh+m+nezdae47V3BXi1BaaUuQ+0wN11q+qqz3lClcoJT2tF'
    'TnaPKxwJrbav4B8pctkth0eb/M7kyJFj08X/A2dMpKe8QPTUAAAAAElFTkSuQmCC'
)

def get_png_data():
    """Return the raw PNG data bytes."""
    return base64.b64decode(_png_base64)

def get_image():
    """Return a PIL Image object (requires Pillow)."""
    import io
    from PIL import Image
    return Image.open(io.BytesIO(get_png_data()))
