# -*- coding: utf-8 -*-
"""Font atlas resource: DejaVu Sans Mono size 20

Font: DejaVu Sans Mono
License: DejaVu Fonts License (permissive, allows embedding)
Homepage: https://dejavu-fonts.github.io/

DejaVu fonts are based on Bitstream Vera fonts. Bitstream Vera fonts
are released to the public domain. DejaVu changes are in public domain.
Glyphs imported from other sources are under compatible permissive licenses.

The full license text is available at:
https://dejavu-fonts.github.io/License.html

This license explicitly permits:
- Embedding in documents and software
- Redistribution with or without modification
- Commercial and non-commercial use

"""
# Generated by scripts/generate_font_atlas.py

import base64

font_name = 'DejaVu Sans Mono'
font_size = 20
char_width = 15
char_height = 26
atlas_width = 240
atlas_height = 156
first_char = 32
last_char = 126
chars_per_row = 16
baseline = 20
ascent = 19
descent = 5

# PNG image data (base64 encoded)
_png_base64 = (
    'iVBORw0KGgoAAAANSUhEUgAAAPAAAACcCAYAAABBYyazAAAq0UlEQVR42u1dd9hdw/Z+50tvQoQk'
    'JARBdK4guhAE8cPVokdvcdWrC4Kr3GgXV4hOEAmiR7RIgojeEkSJHhLSe3l/f+x334xtl9nnO+d8'
    '50vmfZ7v2d/ZM2vanjWzZs3MWoCHh4eHh4eHh4eHh4eHh4eHh8eyCJIzGaBuDppnSTKSxss56BuS'
    'nEvyBv1uTnIRyT6O9J1JjnKMuzfJj0jOIDmC5JYFtFFnkq+Q/INLcE3OND4n+VU1vlMnkotJHuMY'
    'v4fKuWM18uxL8lbPJbnb7Qa1/Z72+6qlqI7bAGgA4DX93lH1e63IDdkZwOMArgWwCoCnAbxMcvUc'
    'aayncu0MYIUabLPrAXwL4AHH+I8BGAugL0nj2apszNsSwAkAPjTGPL+0MnAXAIsBjLB+zwPwVkbj'
    '7EHyJQAvANhGs9p/SW6cQHI4gNeNMQ8bY2YYY/oC+BnAgTnKejSAhgBuB7CyWYLzy9gpdgewA4Ab'
    'jDELXWiMMYsB9AXQCcC+jvmsTnI4yY3iBjKSr5Fcx7NpKs4A0ATAVdGApY2BPzDGTLN+jzbGzE3p'
    'XOcAeB5AVwDLAzAA1gVwsjUQxJLGvMvTlqvoeYkxZlINtdepABYAeDQn3WAAc9RGLpgMYCSAUST/'
    'pYGrAcnLAbwN4B0AEz2PJvbR5QD0AvA5gCeWqjUwya/oiBja+lrDLiB5KMkdSb5BsgPJY0m+lpDn'
    '1iTnkzyYZFOS55CcRXKtmJl9xYQ0eqtY21aznQtaA5NsQ3IhyRcKzHew1s55lg3tSA6QXmKx0lgz'
    'Z77vkvx8GWPgC9VXjqpoJVaB+VSHgdsq6JkClFj7kPxY9RxNcjtbNNW7t0l2TKBvr0HgdZJVNdAp'
    'DlPdLyqQ/kzRH5ODpi3JhywGHkSyvWfg1Po2JvkbyQml5qUaYWArvxOVX0f9Pl2/26fQVGnmHJOX'
    'gRPS25Xkm2LePTLibkhyksp4SQ10jNuV924F0m8r+nsdO+GlJKeSvJrkrST7k+xDchrJf5Fs6hk4'
    'tr5nqJ1PLnfGUzTSmjLlN5jkDxFx/AsHuovVQM+RvELMZ3LmvQvJUSTfItnNIf6mEt0nkPxGs9G+'
    'Zf4+L6re6xdIv7rohzvEXUOSxkb6/b9tJJLrS4nV0TNw7BLvR5K/kGxY7sy/JzmtTHlVaS/1Hv2u'
    'Jwa5xZG+J8lxlrT9G8l7SbbLoOuiPeA3pdF1LesXYt5WJNfWTDzT1nqTHB+K9iVqs/dV19YF0jcV'
    '/WcF0DrtA0sX4YpNS9ROV8bkdVOZ+vUJyu+cmhg9PrVnxBLlsdDx405wTK+bGOdqkr9qEPhbTLxG'
    '2hYZZYugJLfQuxlikL0SZmuSPMV6t5VE+QkkV9K7P0j2L2HbvadytClUMyr6Tz0DlyTfOiS/Jvm7'
    '6/Ki2AV4i+TYWsbA/1sDk1wnFK0T4m4Vo6CZSvIide7DpKTqnLBWPyzyfm/VZwTJzRWnRxlE6A0K'
    'pG/vKkIXudzLhAhN8nC1b+9lYa1wm0TQevp9v0auvGtZm4Ebaw3/hSNtr6jEISbpH3l3gLXmNgnM'
    'PVMzZN0StlmoxNq9QPrtRX+PZ+Ci19GQ/IzkdJKZp/SWhoMcXQCMMsYs0O+dAAw3xjCjodYk+TLJ'
    'A0mGByuM9jb7q23G5Wn7mHd1Ir+HAfgDwJ4AHtdZ5MZaixLADAQnbga7no4qECP13LJA+i0j6VQ6'
    'U7S2JLLDy5hvZyvf7RzJ9gOwPoDbjTFTaqrByrUP3Er5nKvfa+l3rwLWWPMjv6fFHf9LSKud4l9E'
    'shnJQ3RAZKeYuHvr0kUchmt/eRrJViVst/Agx9AC6Z/Me5CjJmfg2sTAquOcUn7/SmLg8HZMJ/0+'
    'Tr83dBRVtpM4+YHKvIjkl9qnbFvAx3pT6XxK8u8pcTchOVAa73nSTF+grYOeqsN9JW67pzRotcxJ'
    '11wdbFgtEks3U5suLnTdXw4GliKVrjsoHn9uvO2qc5CjFtZ3N1dpJUJ3rOj2q0V1DU+ODarwco7U'
    'oLqa58j8jbfNssTAqvPrOkxS1zF+FcmxEvNMLarnU5p9N/Y9fentzFsvgwy8hTr2sTmXLDvWojqG'
    'B32e9L3cw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw6PWQTdkhupA/XSSL5Hc2oGumW72PKjr'
    'fCT5qANdA5IHkXxap4Lm6UL9IJKbZdBWyYjcvbKqMVfni4e4lDkmvTOss6sdMuKm3Uc+ySGvxiQv'
    '09Wx2Sr3nWmWQGQULgtXZ7RXT5kO+l0HHMaQPJ5knYzyNiV5rYwezBPtc4V4pfBIbecVSZ6tc/W/'
    'qk9/5GRAkOSWCTdl5pPcPoO2XwydCwMfl9IZ55PsnkLbOYV2EckDczTcSrLlVXIGJrk8yQ8TaAdX'
    'k4H3SqF/MIUuLd+GOj6Z9I128qxXNAa+K+UbnZtFHJpaeVBX9VayEvw07fwryes0ax5J8qgcDHw4'
    'ycdJ7q8rfo1ktTG0GvFL0lldHQV8UUf81lZHW8O6sP5bjnO+d4mpxuZg4A8L/Ej3WHXbX7Pb8mqL'
    'fxeY5hcasZPaaiPluVCD5gq6WXS4dZWycwLtSQr/Sfaum5JcRYYAKSnCu1opDgNfQ/Lf6tvLqZ1v'
    't6641ksiDK9c/UCyvvW+ruzzkOQ2joXo7srAKWksJ/tSBdk8ssq8nkPczTVj76yBqmQMrIFxof7+'
    'VqSPvqPKfGNKnPAc8+MxYQMUdlwC7WCFHx0T9rx9pdOjJExtNNj/xVSybZEjPKA+xBgzP3wpyxDh'
    'R+9SrkIbY6YD+CamnM711nN6VuMAuAXAs8aYV8tQtT0RWOp42hjzfpHSDBnv/pQ4P+u5OCYsfPdT'
    'Am3oYSLuMv1Hem5XixiiLsn9pOvZuIjprimPkwclzpSFoS6AxgAWIbDoEsvAoYOpT1I+0jplbOQG'
    'ANoDmArgU0eaejJI1x/AWgBeMsb8lEF2JAJnXf8soJjt5d5knkbIAQ4z/iZ6PlekdmoOYH8Anxhj'
    '0iSCUQDeBbCPljjNJeUcCuAgAJ8BeCmB9nc9140JCxmgg0NZCzExU21aK412cjf7HQI/Q7sAmF/E'
    'brsQwPYABgL4QRZO1yhCutcBWA7Aw5rYYis3UI2zT0zYrgp7towidOgT5nyHuFHzOLOk0W2WQddM'
    'jHej9e7TaiqxZqZ1MJKPhOtNaX+/0gDwDcnr5cwqTzud6mo/WOveuyOKyvkkHwhN2ibQnWwtr3bT'
    'GriNtOhhWgMqkYGlee9O8hktk6hB97w4u9jVNWcrvdFZ0guEVkCGasavWwAfXGDpoJqnRXxKEfcg'
    'uao61HcSC3ZQ2CvlYGCt6RbIan+dAhh4Lsn7sqz6SVnwux0vBwO/pC2sliRbaJALNbXfpCiTwna+'
    'JqFTvC/pw7Wt3tdg0sYh7qYyXRvFmyS3SKFrpK2MOPw7S4tdEwws5c8lcjIQDqz3ZtEW0x61ytxf'
    '27GhErBPltOACB8t1sDZNivy/2ZgiRrfi3Ctcs7A6mRTpA1ukZO2vnzO3qn8P0gaAEiuq9nntMh7'
    'JwZOmeF+Fv0OCXEGKXyOvBS2kSSwh6WoON4xv78p/lCHuG2lFJyhnYIVVd5Dpd2cleYtUFrym2SA'
    'fr5sh/WUhwqSfAAVApKraQKgbJQfVyMG0peUp4naaqS1xemiXP1C9djMJZP/KvETYsJCb3b3l5KB'
    '5StnkjpJ22o22lNptptIvqDDH3WLxcCifzCNCa3BJU4bfHyedrO2Fw5xiHtlkkdCy2bUjQXUt1c4'
    'E1cgAy8m+SrJI0g2rsHyNNJA+ZLKlMnAkiBIMtVBva3E+lLPjVIUFV+WsJLrAngFgdPpXYwxP1Yz'
    'ydF6Jlkh7AagI4AFETekYfzxetWyyFX9KqIYtPFFROub2ikAHCIt+xCHfDumKCk/1nO9AuqzVySN'
    'Gocx5nsAqwO4TMq1BwBMlDi7TRlF6C1J3g7gFwADENh7vgrAGsaYLJvj4bLuV1cGfl3PfaP7wAAO'
    '0M/XSsS8HcS8dQF0NcZ8XYRkw0MJs8s40i6HJVttSfaL34wMinFMNskhu4MANEdgBH6OQ/wFKfmG'
    'g/a8vOtSALtL+/oCKgjGmJ+NMX0ArAHg/wCMAHAMgDcsJdYqJegDrXQU8lMAbwM4Uc/9AaxujLlE'
    'A0xmFQrJ/APrJNbKUtCEJ7HGujqjziNCS0n2g87WbpqzvP8heYP81baSqLK+JVouyutC00WElgLq'
    'Oo2wLbQlsyPJN0T7VYoSq451yOQiGR1vGlkDH+1QzpF5DMxZ3u5mag3cQuvag9T2JHl6Cn1fkgdb'
    '5T1QJ79I8o5SapJFW23j7BKtr7D0FAtd1qIFrr1/VT9Zo2yjliwzxp2FXpDVUSyHTEkYkrE2S0OP'
    'BNpHM+guLaANXBg47bzqtKQjiRZ9t5RtqDezDgFIAUeS37oeYZSC782Ucr8rsTyJfkiK1rx5bWBg'
    'W6ok+Xcdwy3mQY61tOY+uLoHOUjupLq+nJcwPF88XRrLl12OUNYQA7ckeZq2m36QdnSSjvftWWDD'
    'uTDwSnIO/o7lXWGCFFRrOuazrfYHp6jc4+WtvrED7XUq4xUFKFMuIfmJBuq5kqwuz8pXHgnvldPp'
    '2drn7J3G9EVm4BrxrlCDiq/CGNjDo0I7dK3wruDh4RHPwN67godHLWVe713Bw8PDw8PDw8PDw8PD'
    'w8PDw8PDw8PDw8PDw8PDw8OjEMjOcYgjHOL3jDn7PEdnbS8n2SRHvi/JRM5M2Xi+MMnGVOQixAKS'
    'E3XJ/+gs20U6g52FW1Poh2bQfpWRf1OSl+pM8yzdfBmu8+h1M+p7QExYtzSLK7K3nYXlM8p8eJ5z'
    '7g5lXkWXORaRPDiBfmLeO90kO1pleygm/P4Mm1ih8f15UTtj1lnwIRll2F3fM7yPMDLJwUFVDHFz'
    'dY4PlcAsueI4xLEN7Iz2LnAcaIjg8nNvAMPt+8kx5TUk7wQwGEBXAC0ANEFg/fEqAP9wyK8ugFYI'
    'LvnfA+D1LHtaNThArgLgPQSX1TdEYG50ZQRmgR9UGyztk0QLAMMQWC091RgzsBTZAOhu3yrS4Lg3'
    'lpgsTkN9AD0LqNuhAIbqezYD0BSByd5n4q6ZVkWINwUwDsDWAM4AsCqAtRGYybyXZO+MzA2APRBY'
    'nfgMwO45rlXdbQQEF9W7IrBT3AnAoSl0pwA4HsAsAKeJERsgsKzxbwDTMvI9EEA9AG3V4N8D2AbA'
    '7Q5l/skko5cD/a4JtB1S2vdRBOZ9P0JgFrWJ6ryjyjy/2D3ZGDPXLhwC+8SIlHlqRhoPRdIYUCDz'
    'NkFgkncDABcZY/qVaJwYo364s/WuCwJLGWMc6OerX+apWzMENsqBwJRsS01IffTupsSJRcbVJskE'
    'SFz42RI1V08pwFYSEe4keYv+39lRhL4rJuy8NFtNsgP9a5KYlZFvrHima3OzFLZ2hgj9Y4GdMBSh'
    'u+ak62a5ZFmhGPV1EaFj4i+U+aHqzKIP5RWh9b3DtrvBIY/qiNCPysBFPyvsdpIfW2VPE6Ef07OL'
    'qwht2Z4bHRP2Spz3DHsGvhHA5BSRs79Ezd1S6h+KzK/qrzpidChKI2UW7SLx8QtjzOBiDLvGmAlY'
    'YmNqvwqTHsNlzH+NMVOWMd1KlZYIuwO4D8DZZcj2CQSG8Ksk/ewDwPVCxcMAZgI4IUd+odGMuDzC'
    'dzv9hYG1rjoAwHXGmAV6tznJUVIofQXgEjFSa4f172sAhiNw2dG9gI/VXF72TtN64+mEqFtY+RUT'
    'b+u5aYX141LVtzbgNgAHA3gKwHHGGJaJgVtrSbkNgDY5GHgmgEcA7JdDAgglvjh7auG7deJm4D30'
    '/xAx0JrqJF9KUbC/ZtLmCPz6xDFdWymOxhpjftUM8RGADrI4mYVjLcuQUwE8C+BHAAem+BBaVc8J'
    'Rf5woTuWVhnxVk3RynZzyOelBNqdMur7bTXqNiiaGSrMIF0MzgUQumx92hizqByZGmM+Ew/8XX8T'
    'MtzXRHGn9DFHOcYP7aBPjgmbHInzJwbeHMC3llh2kZRCJ4oZPwJwckbm3S3xGZH/uxfYhi2sThuH'
    '0AzMnCJ/u7l6NqmwjtwkWt8YH8mjl8LZdwtNBgsB9I1ziVJCPKml1H45Zt9wAHgXwPs5lFkNLQVY'
    'nFIMABrFMXArBLZrQ+wC4OVQnFZhXrM6dtr61xbvXsuxDra10CtI1v8VwM0kkwaP2XGVKgLChpyV'
    'NVOnaKGHOuSTpIUenlHfhtWo24HRzCSBVTI+k77jevWNfmVm4DX0V4hBgf4A1nW0HhryV9y2af24'
    'yarKmsnsgJaIt008OUF8bqQGpta+IUZo1Nw2a6M/MnJNNca8bimRLsgQddsX+aOFs/6vFdaRw/qu'
    'brXVaDFhOyy9uFzS4eUAvpZiqUeZ8h6jpdxvAN4ogH6AJgIXZdYfFv9F0TIS508MPAPBhrHNqCul'
    'JBJFV82CBsDv1tpqOgLNdV0EhyTyrkF+VFnaJZyoeidOM1cEbKXnRxXWkd/Tc7ulgCnrpoiLf5kj'
    '1B/mWGvhW9I8KhZxHUxjTDtjTCtjzOIC6Gcg2LvfH9keN8br2TEmLNQjfRnHwD/Zo7rWrl0jp1C6'
    'pIhuLmvcQrTRy1uL9jit42ti8I4k/16MDyYP6Pvq55AK6/SP6XlKTTrrKhLWSpPqUhjiZQAPaTK5'
    'tZbUNVRmHZkRb4Se+8SEhX1yeBwDvwmgjTovEBxBbALgDnk82BjpJ5NC/zi7x6yvwsMKe7i4ChUT'
    'NSPZCcEJsCoAH2ski37MBQBC28j3kzxFNpubkNyE5FVR74MJ+dWVS9Wj1IiNEbgs+aLCOsKzkjra'
    'I9Bgb6tzyiugevvtJQPJ1+VfeAN9l5Ykz0Bwwm5+gVLOmQicjh9UrIG7xLP4GAAfWkyYhKcBTAGw'
    'tbw6hN4zLhUfTQfweBLDTCN5ifVuc7kKmStXINfppNZlEdq/Wa4k6sSkXSVj4CS5fUx4z4xD8vPS'
    'TnMp/XtS6C9OoEvz6jA6zbWp42WGUSn0BZ3ECiUEGZGPw2KSJ2bUt6yXGUhOLeTCh0OZj1LYxKRv'
    'ZZ3ESkP7CE3HLLdAjiexukben5Ll5EDxjkgp6zHR+FWWnP4fAGeHjqKNMe8ZY7Y1xjQ0xqxljDnX'
    'GLOSMeayBNF4UNz+nNYND+cUo+cj2Nt9AEAnY8yrKaPbYmPMMQg2+V/VCDZLI/vFqlcWFkpJMQyB'
    'yn97Y8wfFTqaT0Cw3341gs39uQj2zZ8DsJ0x5o4KK/Iu0sSO1XeZg8BD4nkATq9GO9yPwCFeKwA3'
    '1wIx+iFk72rAGPOgJNqRCA6DzJLy7P+MMfekjXb15Az5nUq9iePh4ZG99nyO5E+a8lfPuhvr4eFR'
    'eYy8J8lHSH6nNfAsrYcb+dbx8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8PDw8CgxEg7oz9dh'
    'jvtJdnRII86i/N4ZNHdF8lwk7wqvkTxS1gCz8j1CBvim6+99kleTXCchfl+649YY+psU1ismLLyc'
    '0S8mrLvChqbU5SnFOTjy/ncdqjEZbTFFhgiN9a4eybFKd7sYmnokP9dliO0jYaFHhZdS8nxOcU6I'
    'Cevq2M6dMup1cST+oxnxR6r/rlYNnrgvkueVOen3lgnexUneI0rNwDZmkdwihf7QFNrjcjBwFHdk'
    'lLtfCu2PFcbAjcWEM+MM3utm1RR99BaRsNFKt3VKWzRVnE9iwnZW2DvRQYDkWQq7O4bOkByj8F1j'
    'wndQ2McJt9FcGHiRDCkWk4HDG1a31AQDy1bZLJLjSY7Td9+pHAz8o/WuCcmd9HFI8o0E2maaIUjy'
    'WpIrklxBvo2oWbFFBgP31O+6ujJ3jdVwGyXQdlH4TJInkmwtJtmA5KkkX8xR/5lKq65D3IIYWOHD'
    'UmbCLZLameSDCksbRNdXnCcSwgdGfVbp/vRUXRVdMYFuO9G9F8P8b1bjamRoibSvQ9yQgffNkf67'
    'kkZaVZM3uuVhYJLrqD2/1D3zVvL1NZXkhmVjYCuso3XftGlMuItF+RNcGDgS9kbSPUiFX6/ws4pQ'
    '/3Ix8JkK7x0Tdl7SHWaSvRW2v0NHuyYhvK2WNj+SbKx3d4rmqIw6D46K9iT31btnCmjv1pI2vnA5'
    'Y18gA/89nFTKxcBi1m9Ur1Ws9yvLGd2PJItmv6zKJZIxJrx3ahCxSyu4WJTfsYDyhfeLpyaEh4PJ'
    '+FqkbgjXv3FGCsJ3cXaawzqupg6xuiWhhAbB26W1h2yMXYHAaN8/dSH9WACv635tGs5FcE/7SklJ'
    'dRBYblkI4JwC2uE2AMsBOFq2rkqBJxHcQz65HFdkNbk9r3bayRjzs9X2vyEw/Pg7gBfyGHmsNgNL'
    'gdUQgV2qOJceuS3Kp+RVJdeRFwDYHsFF+6QL/WP1PKm22IgyxoxDYKygsz3zaE28rer7fgoDh0xq'
    'K322sJk7Y0C7Ud/kXAQX7RdiiaG4tHJ/g8A4QgcERg+OQuBB8r95TQ+R3A+BofSbjTFvlrCticDw'
    'QTMEXj5K/W1nGmM2N8Z0NMb8EhM+2RiziTFmwyxncEVhYK2Bd8QSY2qj42xToQCL8jG4V5YsFyEw'
    'sncVApOe3VIqezcCb4J7AvheVyBPddGYV8As3EAMG6IzAjtkLya4DRkfYdJOACZqMOgUCfsypZMt'
    'UGduLLprJWG54Ep9z94I3Jv+gcDUax7mXV6z73gEDgRKjUcAfAPg9KXAEKATA69qmYWdicAK3kYI'
    'TKEkrTVdLMrnNUb+A4DzjDEfpI14CHzWPIDArG0PBJYKx2kbYaMKbfcXYsToNPEZxphpCGx12ww8'
    'Wn9bWLPzTGPMxIz8Z2GJlU9n00Eqw2UI/AW1Q2CvOa/pob4IzOAcU0LR2S7zIgDXagI5aVlgYBsL'
    'ERi1fgiBbaoktx0uFuXnZeR1tKxYNhEjrgTg2TR3pvpAPxljjkJgc3dXzQgfIbCdPDyPa8liL4lS'
    'wl7VwNbFetcFgTO4YSl04y0R+m8WA28m732rZekDpKS7XeX7CcBlJFfOUa87VE7AzYeynXcXrblv'
    'McaMKuO3uE91PYtkg6WdgW13IfVk1PoIY8zYlHRcLMpPchwxZ8vjem8x86U56F6W0b3NJKa1AHBq'
    'CdptUXXiSHIYBaCTtuAaSYQeY4z5PYOBW5FcT3UbDeAttdP6CJyUf5lRrn8gMIrXT6J0c60TXWe0'
    'hVhiaH1BDuZtpDX31wAuLLPeYb5m/jYAjlmWZmBX5LYo74DbtN46LLSUmVN5EWpV1y9Bu4XWBePs'
    'XIcHNGY7iNF1AeygtXADLNFQp7WzQeByZhGAdwF8IAloL6UxPoWJ2kpCmQzgYmPMkwisHx5NcssS'
    '97U+ANaU6Dy7Bvr6nZpEzl2a7LwVi4Ff1zPNovzrOZlwjpRU9QGcUkCZQq334hK0W+ijaO2YsLUj'
    'cVzWwanr35iBcj8AnxhjZmkW/ABL/EilidA3I9h6O9/yRBluAd3icmy1oLUEuTkCY+y3GmNG1ERH'
    '16BxEwKj+IctbWvh1IMcDrT2Saw/WZTXuykJvo2yDnK01zG730g2jAk/meTdJPciuZYMkK+s87uT'
    'le5JjnXIc5Cjgw61zJWB8WY6xniIjs/R5cSNzpl/oGOSk7SOTYu/mbX3e7v1/nqVhyQ7J9DuaRmt'
    'j56meiTtwExMWgul5HSJW5fkh3IO0KQa/TP3QY6YNJbTaahxWW0doetWyFnoWsPAoj8s4ZzrwjjL'
    '+i4MrPBnFX5sTNg5GWdsR7sqLfIwsOL3LdTjgJXGHWK8hSQfcojf1MrjKOv9gdb7FePWnzodtCju'
    '0oAGyrnyrtG8yAx8nOOZ816lZmClc2WSt4fayMDFEqFhjBmgddgo/NkCfW9jzOBqJH2bnqcnhB0C'
    '4CkAXyHQdM9EcBDiAgSnYeaVouGMMecgOMwwBsEW2xwE3gOPM8b0ckzmBa1p6zisf0PlV7hFZO8I'
    'vKXnlAQl2MUI/Nv2l9PpaLoTANwCYGXk3Nd1QMsK6/M3qX9eCI/UUWsHjdTTSK7vW8Sjmv2pKDOw'
    '0rpBae251IjQJWr08HD+eJL1fTf0KAIDO10nLFKe1boPXA6UWp1+HYI9x8e0F+fh4VHMpZxvAg+P'
    'ipAwmJOkmTFmZpVvOg8PDw8PDw8PDw8PDw8PDw8PDw8Pj/JAZ20/05nYlXyLeHjUPiZeRzc2nixT'
    'fm11ymVIBbXBfa43ioqQVxuSA0j+bJ346VmCfFor7WeLkNazWUbmU2g75DlJRXKI4nfMmc8ZMRcm'
    'tlva+PUv+8DGmC8BHA5gnyxbwR5FwQMADkVgLcLDo2gjdm9dRFitxPksszOwdT3wC9l5NiXMq2gz'
    'cJm/RUEzcCSNm5aZGdiaifsYY5obY773w1nJ0FbP0caY7xLMyXp45GfgAka59WQZ4iNdjp8q065H'
    '5EhjQ3k3nE3yB/lZauRIe7hopyj/93QbqlEKTT2Sl5H8Vj503pT5F9fybkXySVnTmC+rE1enWZ6w'
    'ZkICGKfXR0bWaj1T6OuSvITkBJX5LZKd8kgN8of0sNpqqqyaNM6guSxmTdnasZ22i6F9tBp9rY48'
    'ZpLkdSWY9adqnX+N+tIwSUv/0u9PSa6bJekU0s5K4xAZo5gpCy9jSqEXiWY6McXawpUOIvSrJH+J'
    'oX0uI19D8qGUvA9PoX04Jv4Uks9nMYMskCxMyPOtpOuTNgOnII2B74mJ/zvJp9PKbOX7gga3KPpX'
    'IgNHRWgNYI/qXZ9SiNBitsmR8g6N/H68RO18fkq/uKKUDPwKydOlZawvm1jd1RBzkuwzWwzM0Bi7'
    'bEztY9nZ2jsl3+MVZxrJXlpLNtZsfqnceMTR7WDRHUyyuaSIl6zyJDFDO9VpqjzstZI9rk1Ivija'
    'Ux3abEPFvc+xjTtb3hiPVBt30Gi/yJGB58r38vpq58NEOyeHtFMjWmj1qyf1+/xSrYH1XWfLy+XG'
    'JOeFjuVkc+0bkhOL3c7ihQWKd6F2KFqRPNt6v3a5lRDXqkK7ZTDwPNubm8J6Kez+lPQ/UJyDcpbr'
    'P6K7IPK+hWUfa8OM2eiQmLAWaugXS8DAN8Z5NtTgM92RgWdHDblrtqCcnVUqA29qSUanl1KJJQYe'
    'bf3+xHaaTvIBpVevmO1M8rSktrFsx51fqjXwqiRvkUZ1jrXOO1dRlstI4hPbm5sQMsH6CXnWR2Aw'
    'YIYx5rGcRQ7THBZR3v0B4O0M2q30fFBi9CL9LUbgfa4KSzwoFBMhcz4fKfM0BLa5XPCpPOXZCE3R'
    'Ll/B+pqHAewBYBqAQWXIz3YZMxWBvbFQyThNz8ZFbucN9IxbNj4fxwtVxWJeBAbdeiGwxxznBynL'
    '+kec54awAZKcUjVDYJTghwKK3dQh3ySEH6CO/qr0Z28DlcKEULOUMk9yTCOubvMdv1FNogMCFynN'
    'NXCW+i67bU98UczvrPYqpJ2bptD+GjcRFqsRTkPgsOp5zU7NQ98sCLwMuiDu6GYogkxPoJmBwM1H'
    'IbPdDId8kzBVz/VMMjqUoFPNSCnf0n709QhjzNGafXcGcF6eOaZEZSr2vv3MlO/bKtIHisrAYWc9'
    'xxgzxhgzXTNzFYCujmlsFF0DAwjXzbF+mWRn6yMAzfKugQF8pueu0TWsJSIn4R099y9zJ/5Uzz2i'
    'a2CHMtd2fKTniZK4+pB0rfNkx4G5phH2871iwvaK44ViMfB3ep6ltXBDufZ8GIGjMRfUBzBQip1m'
    '0jyHNorT1jz99Owvpddq0kJvIE3evgl0YZrnyzD6ctqqGIjAWVga7kZgg/pSkn1Irq06ryYvEQNI'
    'nlCCDxyu88+1tNBrARiA/O5bayXkEuYI9d2Hkzx+RBDut58RM0lUEp5E4BH0QPXd1tJ6nwXgSInx'
    'jxc9V6n458TsW02yNIA9EmjtfeCfY9J4OiNvY7kGybsP/GDCnupzDvvAR0i1n4QzHNotlxZaNPfF'
    '5PUbySf0/wYJdIlHKS0vE10TaLs67F0Pdix/US4z6FAFSQ5wSKOuDtk47WOHBzms38NtjyVWn25Z'
    'zHZWnItS2vhf0fhVRRoVP0fg3/ZVAFOkpXsGgde9iY7JTJfIPBKBt70fEThmPigjbyK4DNATwAjl'
    'PRuBw68zAKR1rGMQOKz+TjPqaInUkxzq/CCArTUr/gJgAYDvpQc4HIEf3VLgeJX5e7XTW2q3UEEy'
    'B7UD1V2XXqqlzKFZl27kErW7+ue8Sm4UY8xV6j+2x493ARxrjPHeJJZGSAoZq+OcDSu8rNtoNrnZ'
    'f7nqo65vglrHrL01ew1B4A9qJQBnA1gPwIvGmLkVXPYVsUR7/Ln/mh7LIgPfmrA+mklykwos76YJ'
    'eoZm/mt6LIsM3FJHOT+W4nAyycfLYT2kCAw8X7dstvJf0sPDw8PDw8PDw8PDw8PDw8PDw8PDw8PD'
    'w8PDw8NDlxL6kBwXWi7NQfspya9yxB+nffbPSV4VZz7Ho3I6xrsy/+NR2d/pzMiJrh9LyMCfR/I6'
    'pxLbpMp3C49ahN31PBOB1Ze2pcrIGNMRgfmakyN5e/gZ2KPA7xRaIG1cAG2uGdiiq5Lhwo8rega2'
    'L1rrovkIrQG+I3klyQYOle2ltcNceWjYxTLB2j2DNjRo3YNke5KDSf5B8nuSN6Rdk5O93hG62D6D'
    '5PtKr3kKzVDLcubmehdFki3r6lyOD9dvTWPCGugy+XdRP0lqhx8cvsHnOh8dpb88yZ4yyX8qrG9C'
    'mqNldbNdQvgnMgu8Ugp9Glz9HtXT7Di7XAxijFmM4N51/Uof3UIGflH+gaMYlEF/RQzNXJIDczLw'
    'yTKcHUW3BLoTUzrGZS4MnIJSMPAlCj8sJmw/hV0dExZaHVklpU7Lk1wcZ8VEM8lrsiLS2Xrfybpk'
    'UC8h3dD1y8UxYZsr7JGUcqUx8DxXMzeaRVlg/y5oBhbtDJIVef0xbg28GwKDbxsgMOG5PwIrjAeQ'
    '3Dmhgu0AnI/Ans/pAFoCWBOBfam8xuZOBfAzAmsXDQGspbST7rkep+c5CO7GNkZgK/oqLLEeGTey'
    'drMsZ76nd1FMLkGbP6xnnImhHpE4NkbpmXaTZ0sElhJHJcwkhyKwd/yIjME3BfAIgFkAehhjFiSk'
    '+xgCe9dxli/Cd/1S2rpztGEl9cwCcFyMPfAkrIyIVcYyYRYq3eqnNQPPjopClvbv9gTa0+I8KEjt'
    'PyHnDDw5TfRNWBctIFmnXGvgItg9elszzwrWuyZyZPVxAk14Le/aiFg90fIY0Ftxtk3JezfN0gMt'
    'DwP7OdS5b9S7gZzDTSI5Nmd7r0ryJ5JXOcZfUY7qSHJUDczAw5T3hTJKkBSvrpaRY+QpY4ok2l4k'
    '15Cxxc3lmG2jUjHwqJiw0PjaiATa21PEwrtzMvD1Oct9oeielAi6Wl4/uzXAwKcrzrHWu0PTfP5I'
    'BJ5Gcrh+r6v4i8OL/DLGNzdLX2EZhHM2baP+sZjkXTEi/z9ytF1jOf0a5PKdIts5n5DcrAYYeENL'
    'gZa4fWXxkAs2LZUInWb1P8mKQprHgN9ylunLnPGvRmAreBUEpmK/AzCJ5H/zzORlxqMIrPv3iIjP'
    'lEibpEx5C0AnSRu7AvhE4v+ulgj9jjEmy3DbwIT/05Q5XwF4CcBBlhb4KAQGBB9wZAQD4CHV/cgC'
    '/CHX1E7BYvzZM0NavHu0/GsGoLWWkA8hMHw4G8CHAE7BErvkZZ2BRybQ9iviDNyjGnWoT3JLkrcp'
    'rWdKNAOvpPSHxYQ9mDUDW2LZQtn9XV4i9cgMmlABtrHMrV6nk0nDSK6lsGscZsDPLBHva9eBjuS+'
    'yuMIWQaZT/LuHO12rfw+t8n5XVupriT5Rg2K0P9WWQwqDRlr4DMUdkcC7T/i7BsXuAbuUaT6fKy1'
    'cT2HuG8p76aOaTeQOPl1TH2/dWTgnqEbUrkoJcmTMmi6KN4pEqd3kZXHOVYaWe0c2pU+nOQBLjsM'
    'Fm0dMeAr1jfv7Eh7tLS5mxb4PeuozjNqgIEnqux1UKmIyO+vyFduM426oZ/eXRNoV9NsskAdsoX8'
    '9N6vjl4yBpbR7TPlV7ix8j5RZZnhuM4aFG475ZiNxoXuSaXRXV3MMceRgZdT3JHySTw/TUFizZ4L'
    'NIPOlMRRR/vln6mtW2QwEUk+YL27U+96Odb7EuXzjevWCskdVdf/q2YfHVeD20jja4sWeliMd3KS'
    'fCKDvk/CHt/AEjPw5BRFgasH90Py7AOL5p8x8X8i2d+FgZXGYDHDwhzi/pjo8sBq489S6DaQlvsr'
    '2yIkyUZi/rkkN3fIv43lkeIih/hV1gRQrYMcNbgPPLM27QP/gWAv+C0EVux/kKLokAwlR28EXgq/'
    'EN0nCBwyjStxHXYEcBMCx1+zpTQbgWBfs7ejguYRBPvIXyLwsOCC6xF4jpiEYJ9wKICdsMR3rAsG'
    'INi3rYP4vd84hDqKoda7FyJhf5m5Eezl1gNwiDFmhlX3OZYCbWCWryFjzC/qE5RyxqWPtSjSt15g'
    '1adcE1sVgAZY4vmi4mfgR4ucrtNRSo/aAa27SfLVGsj7ReV9Wl670oXMwFpChif9Xq4tM7CHR+Ig'
    'L2kHAO6qgSK8qOd/AEzPc52wgLp+jsBfV79I3hUF71rFw6Uzd8ISn8hA4BZlUA0U5RYEx3T3B7Aa'
    'SrsvTC0FvwfwBICbPQN71HbMReA98sSUc9Mlg/K8UH+lzms9/7k9PCpHiihYC+3h4eFREvw/yele'
    'cPP8WQAAAAAASUVORK5CYII='
)

def get_png_data():
    """Return the raw PNG data bytes."""
    return base64.b64decode(_png_base64)

def get_image():
    """Return a PIL Image object (requires Pillow)."""
    import io
    from PIL import Image
    return Image.open(io.BytesIO(get_png_data()))
